<?php
			$optionsArray = array( 'fields' => array( 'gridFields' => array( 'ca_codcuenta',
'ca_nomcuenta',
'ca_recibemovto',
'tac_vidautil',
'tac_codcta',
'nicsp_cuentadepcod',
'nicsp_cuentacostonew',
'nicsp_cuentacostoservicio',
'nicsp_cuentacostocodnopp',
'nombrecuenta' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'ca_codcuenta' => array( 'import_field2' ),
'ca_nomcuenta' => array( 'import_field3' ),
'ca_recibemovto' => array( 'import_field4' ),
'tac_vidautil' => array( 'import_field8' ),
'tac_codcta' => array( 'import_field9' ),
'nicsp_cuentadepcod' => array( 'import_field12' ),
'nicsp_cuentacostonew' => array( 'import_field14' ),
'nicsp_cuentacostoservicio' => array( 'import_field15' ),
'nicsp_cuentacostocodnopp' => array( 'import_field16' ),
'nombrecuenta' => array( 'import_field' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'import_header' ),
'grid' => array( 'import_field2',
'import_field3',
'import_field4',
'import_field8',
'import_field9',
'import_field12',
'import_field14',
'import_field15',
'import_field16',
'import_field' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'import_header' => 'top',
'import_field2' => 'grid',
'import_field3' => 'grid',
'import_field4' => 'grid',
'import_field8' => 'grid',
'import_field9' => 'grid',
'import_field12' => 'grid',
'import_field14' => 'grid',
'import_field15' => 'grid',
'import_field16' => 'grid',
'import_field' => 'grid' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'import_header' => array( 'import_header' ),
'import_field' => array( 'import_field2',
'import_field3',
'import_field4',
'import_field8',
'import_field9',
'import_field12',
'import_field14',
'import_field15',
'import_field16',
'import_field' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false,
'menus' => array(  ),
'calcTotalsFor' => 1 ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'import',
'type' => 'import',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'import-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_header' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'import-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_field2',
'import_field3',
'import_field4',
'import_field8',
'import_field9',
'import_field12',
'import_field14',
'import_field15',
'import_field16',
'import_field' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'import_header' => array( 'type' => 'import_header' ),
'import_field2' => array( 'field' => 'ca_codcuenta',
'type' => 'import_field' ),
'import_field3' => array( 'field' => 'ca_nomcuenta',
'type' => 'import_field' ),
'import_field4' => array( 'field' => 'ca_recibemovto',
'type' => 'import_field' ),
'import_field8' => array( 'field' => 'tac_vidautil',
'type' => 'import_field' ),
'import_field9' => array( 'field' => 'tac_codcta',
'type' => 'import_field' ),
'import_field12' => array( 'field' => 'nicsp_cuentadepcod',
'type' => 'import_field' ),
'import_field14' => array( 'field' => 'nicsp_cuentacostonew',
'type' => 'import_field' ),
'import_field15' => array( 'field' => 'nicsp_cuentacostoservicio',
'type' => 'import_field' ),
'import_field16' => array( 'field' => 'nicsp_cuentacostocodnopp',
'type' => 'import_field' ),
'import_field' => array( 'field' => 'nombrecuenta',
'type' => 'import_field' ) ),
'dbProps' => array(  ),
'version' => 14,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'listTotals' => 1 );
		?>