<?php
			$optionsArray = array( 'pdf' => array( 'pdfView' => false ),
'details' => array( 'alelemdevolutivo' => array( 'displayPreview' => 2,
'previewPageId' => '' ),
'alelemconsumo' => array( 'displayPreview' => 2,
'previewPageId' => '' ) ),
'fields' => array( 'gridFields' => array( 'tac_codcta',
'ca_recibemovto',
'tac_vidautil',
'ca_codcuenta',
'ca_nomcuenta',
'nicsp_cuentacostonew',
'nicsp_cuentacostoservicio',
'nicsp_cuentadepcod',
'nicsp_cuentacostocodnopp',
'nombrecuenta' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'tac_codcta' => array( 'integrated_edit_field8' ),
'ca_recibemovto' => array( 'integrated_edit_field3' ),
'tac_vidautil' => array( 'edit_field_label',
'integrated_edit_field7',
'edit_field_tooltip' ),
'ca_codcuenta' => array( 'integrated_edit_field1' ),
'ca_nomcuenta' => array( 'integrated_edit_field2' ),
'nicsp_cuentacostonew' => array( 'edit_field_label1',
'integrated_edit_field13',
'edit_field_tooltip1' ),
'nicsp_cuentacostoservicio' => array( 'edit_field_label2',
'integrated_edit_field14',
'edit_field_tooltip2' ),
'nicsp_cuentadepcod' => array( 'edit_field_label3',
'integrated_edit_field11',
'edit_field_tooltip3' ),
'nicsp_cuentacostocodnopp' => array( 'edit_field_label4',
'integrated_edit_field15',
'edit_field_tooltip4' ),
'nombrecuenta' => array( 'integrated_edit_field' ) ) ),
'pageLinks' => array( 'edit' => true,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'above-grid' => array(  ),
'below-grid' => array( 'view_back_list',
'view_close',
'hamburger' ),
'supertop' => array( 'expand_menu_button',
'collapse_button',
'loginform_login',
'username_button' ),
'left' => array( 'logo',
'expand_button',
'menu' ),
'top' => array( 'view_header' ),
'grid' => array( 'tabs',
'integrated_edit_field' ),
'section' => array( 'integrated_edit_field8',
'integrated_edit_field3',
'edit_field_label',
'integrated_edit_field7',
'edit_field_tooltip',
'integrated_edit_field1',
'integrated_edit_field2' ),
'section1' => array( 'text',
'edit_field_label1',
'integrated_edit_field13',
'edit_field_tooltip1',
'text1',
'edit_field_label2',
'integrated_edit_field14',
'edit_field_tooltip2' ),
'section2' => array( 'text2',
'edit_field_label3',
'integrated_edit_field11',
'edit_field_tooltip3',
'text3',
'edit_field_label4',
'integrated_edit_field15',
'edit_field_tooltip4' ) ),
'formXtTags' => array( 'above-grid' => array(  ) ),
'itemForms' => array( 'view_back_list' => 'below-grid',
'view_close' => 'below-grid',
'hamburger' => 'below-grid',
'expand_menu_button' => 'supertop',
'collapse_button' => 'supertop',
'loginform_login' => 'supertop',
'username_button' => 'supertop',
'logo' => 'left',
'expand_button' => 'left',
'menu' => 'left',
'view_header' => 'top',
'tabs' => 'grid',
'integrated_edit_field' => 'grid',
'integrated_edit_field8' => 'section',
'integrated_edit_field3' => 'section',
'edit_field_label' => 'section',
'integrated_edit_field7' => 'section',
'edit_field_tooltip' => 'section',
'integrated_edit_field1' => 'section',
'integrated_edit_field2' => 'section',
'text' => 'section1',
'edit_field_label1' => 'section1',
'integrated_edit_field13' => 'section1',
'edit_field_tooltip1' => 'section1',
'text1' => 'section1',
'edit_field_label2' => 'section1',
'integrated_edit_field14' => 'section1',
'edit_field_tooltip2' => 'section1',
'text2' => 'section2',
'edit_field_label3' => 'section2',
'integrated_edit_field11' => 'section2',
'edit_field_tooltip3' => 'section2',
'text3' => 'section2',
'edit_field_label4' => 'section2',
'integrated_edit_field15' => 'section2',
'edit_field_tooltip4' => 'section2' ),
'itemLocations' => array( 'tabs' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field8' => array( 'location' => 'section',
'cellId' => 'c1' ),
'integrated_edit_field3' => array( 'location' => 'section',
'cellId' => 'c2' ),
'edit_field_label' => array( 'location' => 'section',
'cellId' => 'c3' ),
'integrated_edit_field7' => array( 'location' => 'section',
'cellId' => 'c3' ),
'edit_field_tooltip' => array( 'location' => 'section',
'cellId' => 'c3' ),
'integrated_edit_field1' => array( 'location' => 'section',
'cellId' => 'c4' ),
'integrated_edit_field2' => array( 'location' => 'section',
'cellId' => 'c5' ),
'text' => array( 'location' => 'section1',
'cellId' => 'c1' ),
'edit_field_label1' => array( 'location' => 'section1',
'cellId' => 'c1' ),
'integrated_edit_field13' => array( 'location' => 'section1',
'cellId' => 'c1' ),
'edit_field_tooltip1' => array( 'location' => 'section1',
'cellId' => 'c1' ),
'text1' => array( 'location' => 'section1',
'cellId' => 'c' ),
'edit_field_label2' => array( 'location' => 'section1',
'cellId' => 'c' ),
'integrated_edit_field14' => array( 'location' => 'section1',
'cellId' => 'c' ),
'edit_field_tooltip2' => array( 'location' => 'section1',
'cellId' => 'c' ),
'text2' => array( 'location' => 'section2',
'cellId' => 'c1' ),
'edit_field_label3' => array( 'location' => 'section2',
'cellId' => 'c1' ),
'integrated_edit_field11' => array( 'location' => 'section2',
'cellId' => 'c1' ),
'edit_field_tooltip3' => array( 'location' => 'section2',
'cellId' => 'c1' ),
'text3' => array( 'location' => 'section2',
'cellId' => 'c' ),
'edit_field_label4' => array( 'location' => 'section2',
'cellId' => 'c3' ),
'integrated_edit_field15' => array( 'location' => 'section2',
'cellId' => 'c3' ),
'edit_field_tooltip4' => array( 'location' => 'section2',
'cellId' => 'c3' ) ),
'itemVisiblity' => array( 'expand_menu_button' => 2,
'expand_button' => 5 ) ),
'itemsByType' => array( 'view_header' => array( 'view_header' ),
'view_back_list' => array( 'view_back_list' ),
'view_close' => array( 'view_close' ),
'hamburger' => array( 'hamburger' ),
'view_edit' => array( 'view_edit' ),
'tabs' => array( 'tabs' ),
'integrated_edit_field' => array( 'integrated_edit_field8',
'integrated_edit_field3',
'integrated_edit_field1',
'integrated_edit_field2',
'integrated_edit_field' ),
'edit_field_label' => array( 'edit_field_label',
'edit_field_label1',
'edit_field_label2',
'edit_field_label3',
'edit_field_label4' ),
'edit_field' => array( 'integrated_edit_field7',
'integrated_edit_field13',
'integrated_edit_field14',
'integrated_edit_field11',
'integrated_edit_field15' ),
'edit_field_tooltip' => array( 'edit_field_tooltip',
'edit_field_tooltip1',
'edit_field_tooltip2',
'edit_field_tooltip3',
'edit_field_tooltip4' ),
'text' => array( 'text',
'text1',
'text2',
'text3' ),
'logo' => array( 'logo' ),
'menu' => array( 'menu' ),
'username_button' => array( 'username_button' ),
'loginform_login' => array( 'loginform_login' ),
'userinfo_link' => array( 'userinfo_link' ),
'logout_link' => array( 'logout_link' ),
'expand_menu_button' => array( 'expand_menu_button' ),
'collapse_button' => array( 'collapse_button' ),
'expand_button' => array( 'expand_button' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'c3' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'tabs',
'integrated_edit_field' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 1 ),
'section' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field8' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c4' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field1' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c5' => array( 'cols' => array( 1 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field2' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c2' => array( 'cols' => array( 0 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field3' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c3' => array( 'cols' => array( 1 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'edit_field_label',
'integrated_edit_field7',
'edit_field_tooltip' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 2,
'height' => 3 ),
'section1' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'text',
'edit_field_label1',
'integrated_edit_field13',
'edit_field_tooltip1' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'text1',
'edit_field_label2',
'integrated_edit_field14',
'edit_field_tooltip2' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 2 ),
'section2' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'text2',
'edit_field_label3',
'integrated_edit_field11',
'edit_field_tooltip3' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'text3' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c3' => array( 'cols' => array( 0 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'edit_field_label4',
'integrated_edit_field15',
'edit_field_tooltip4' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 3 ) ) ),
'loginForm' => array( 'loginForm' => 0 ),
'page' => array( 'verticalBar' => true,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false,
'menus' => array( array( 'id' => 'main',
'horizontal' => false ) ),
'calcTotalsFor' => 1 ),
'misc' => array( 'type' => 'view',
'breadcrumb' => false,
'nextPrev' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'view',
'type' => 'view',
'layoutId' => 'leftbar',
'disabled' => 0,
'default' => 0,
'forms' => array( 'above-grid' => array( 'modelId' => 'view-above-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1',
'colspan' => 2 ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'view-below-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'view_back_list',
'view_close' ) ),
'c2' => array( 'model' => 'c2',
'items' => array( 'hamburger' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'supertop' => array( 'modelId' => 'leftbar-top-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'expand_menu_button',
'collapse_button' ) ),
'c2' => array( 'model' => 'c2',
'items' => array( 'loginform_login',
'username_button' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'left' => array( 'modelId' => 'leftbar-menu',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c0' ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c0' => array( 'model' => 'c0',
'items' => array( 'logo',
'expand_button' ) ),
'c1' => array( 'model' => 'c1',
'items' => array( 'menu' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'view-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'view_header' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c3' ) ),
'section' => '' ) ),
'cells' => array( 'c3' => array( 'model' => 'c3',
'items' => array( 'tabs',
'integrated_edit_field' ) ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c' ) ),
'section' => '' ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c4' ),
array( 'cell' => 'c5' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c2' ),
array( 'cell' => 'c3' ) ) ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field8' ) ),
'c' => array( 'model' => 'c1',
'items' => array(  ) ),
'c2' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field3' ) ),
'c3' => array( 'model' => 'c3',
'items' => array( 'edit_field_label',
'integrated_edit_field7',
'edit_field_tooltip' ) ),
'c4' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field1' ) ),
'c5' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field2' ) ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section1' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c' ) ) ) ),
'cells' => array( 'c1' => array( 'model' => 'c3',
'items' => array( 'text',
'edit_field_label1',
'integrated_edit_field13',
'edit_field_tooltip1' ),
'useFullWidth' => true ),
'c' => array( 'model' => 'c3',
'items' => array( 'text1',
'edit_field_label2',
'integrated_edit_field14',
'edit_field_tooltip2' ),
'useFullWidth' => true ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section2' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c3' ) ) ) ),
'cells' => array( 'c1' => array( 'model' => 'c3',
'items' => array( 'text2',
'edit_field_label3',
'integrated_edit_field11',
'edit_field_tooltip3' ),
'useFullWidth' => true ),
'c' => array( 'model' => 'c3',
'items' => array( 'text3' ) ),
'c3' => array( 'model' => 'c3',
'items' => array( 'edit_field_label4',
'integrated_edit_field15',
'edit_field_tooltip4' ),
'useFullWidth' => true ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ) ),
'items' => array( 'view_header' => array( 'type' => 'view_header' ),
'view_back_list' => array( 'type' => 'view_back_list' ),
'view_close' => array( 'type' => 'view_close' ),
'hamburger' => array( 'type' => 'hamburger',
'items' => array( 'view_edit' ) ),
'view_edit' => array( 'type' => 'view_edit' ),
'tabs' => array( 'type' => 'tabs',
'titles' => array( array( 'text' => 'Inf. Cuenta',
'type' => 0 ),
array( 'text' => 'Inf. Contable',
'type' => 0 ),
array( 'text' => '...Más',
'type' => 0 ) ),
'locations' => array( 'section',
'section1',
'section2' ),
'bsStyle' => 'default',
'panelType' => 2 ),
'integrated_edit_field8' => array( 'field' => 'tac_codcta',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field3' => array( 'field' => 'ca_recibemovto',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'edit_field_label' => array( 'type' => 'edit_field_label',
'field' => 'tac_vidautil',
'separated' => true ),
'integrated_edit_field7' => array( 'field' => 'tac_vidautil',
'type' => 'edit_field',
'orientation' => 0,
'joined' => false,
'separated' => true ),
'edit_field_tooltip' => array( 'type' => 'edit_field_tooltip',
'field' => 'tac_vidautil',
'separated' => true,
'tooltip' => array( 'field' => 'tac_vidautil',
'table' => null,
'type' => 4 ) ),
'integrated_edit_field1' => array( 'field' => 'ca_codcuenta',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field2' => array( 'field' => 'ca_nomcuenta',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'text' => array( 'type' => 'text',
'label' => array( 'text' => '<p><strong>PROPIEDADES, PLANTA Y EQUIPO | BIENES MUEBLES EN BODEGA</strong></p>',
'type' => 0 ),
'editedByRte' => true ),
'edit_field_label1' => array( 'type' => 'edit_field_label',
'field' => 'nicsp_cuentacostonew',
'separated' => true,
'label' => array( 'field' => 'nicsp_cuentacostonew',
'table' => 'alcuentasalma',
'type' => 3 ) ),
'integrated_edit_field13' => array( 'field' => 'nicsp_cuentacostonew',
'type' => 'edit_field',
'orientation' => 0,
'joined' => false,
'separated' => true ),
'edit_field_tooltip1' => array( 'type' => 'edit_field_tooltip',
'field' => 'nicsp_cuentacostonew',
'separated' => true,
'tooltip' => array( 'field' => 'nicsp_cuentacostonew',
'table' => null,
'type' => 4 ) ),
'text1' => array( 'type' => 'text',
'label' => array( 'text' => '<p><strong>PROPIEDADES, PLANTA Y EQUIPO | EN SERVICIO</strong></p>',
'type' => 0 ),
'editedByRte' => true ),
'edit_field_label2' => array( 'type' => 'edit_field_label',
'field' => 'nicsp_cuentacostoservicio',
'separated' => true,
'label' => array( 'field' => 'nicsp_cuentacostoservicio',
'table' => 'alcuentasalma',
'type' => 3 ) ),
'integrated_edit_field14' => array( 'field' => 'nicsp_cuentacostoservicio',
'type' => 'edit_field',
'orientation' => 0,
'joined' => false,
'separated' => true ),
'edit_field_tooltip2' => array( 'type' => 'edit_field_tooltip',
'field' => 'nicsp_cuentacostoservicio',
'separated' => true,
'tooltip' => array( 'field' => 'nicsp_cuentacostoservicio',
'table' => null,
'type' => 4 ) ),
'text2' => array( 'type' => 'text',
'label' => array( 'text' => '<p><strong>DEPRECIACIÓN ACUMULADA DE PROPIEDADES, PLANTA Y EQUIPO (CR)</strong></p><p><br></p>',
'type' => 0 ),
'editedByRte' => true ),
'edit_field_label3' => array( 'type' => 'edit_field_label',
'field' => 'nicsp_cuentadepcod',
'separated' => true,
'label' => array( 'field' => 'nicsp_cuentadepcod',
'table' => 'alcuentasalma',
'type' => 3 ) ),
'integrated_edit_field11' => array( 'field' => 'nicsp_cuentadepcod',
'type' => 'edit_field',
'orientation' => 0,
'joined' => false,
'separated' => true ),
'edit_field_tooltip3' => array( 'type' => 'edit_field_tooltip',
'field' => 'nicsp_cuentadepcod',
'separated' => true,
'tooltip' => array( 'field' => 'nicsp_cuentadepcod',
'table' => null,
'type' => 4 ) ),
'text3' => array( 'type' => 'text',
'label' => array( 'text' => '<p><strong>BIENES Y DERECHOS RETIRADOS</strong></p><p><br></p>',
'type' => 0 ),
'editedByRte' => true ),
'edit_field_label4' => array( 'type' => 'edit_field_label',
'field' => 'nicsp_cuentacostocodnopp',
'separated' => true,
'label' => array( 'field' => 'nicsp_cuentacostocodnopp',
'table' => 'alcuentasalma',
'type' => 3 ) ),
'integrated_edit_field15' => array( 'field' => 'nicsp_cuentacostocodnopp',
'type' => 'edit_field',
'orientation' => 0,
'joined' => false,
'separated' => true ),
'edit_field_tooltip4' => array( 'type' => 'edit_field_tooltip',
'field' => 'nicsp_cuentacostocodnopp',
'separated' => true,
'tooltip' => array( 'field' => 'nicsp_cuentacostocodnopp',
'table' => null,
'type' => 4 ) ),
'logo' => array( 'type' => 'logo' ),
'menu' => array( 'type' => 'menu' ),
'username_button' => array( 'type' => 'username_button',
'items' => array( 'userinfo_link',
'logout_link' ) ),
'loginform_login' => array( 'type' => 'loginform_login' ),
'userinfo_link' => array( 'type' => 'userinfo_link' ),
'logout_link' => array( 'type' => 'logout_link' ),
'expand_menu_button' => array( 'type' => 'expand_menu_button' ),
'collapse_button' => array( 'type' => 'collapse_button' ),
'integrated_edit_field' => array( 'field' => 'nombrecuenta',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'expand_button' => array( 'type' => 'expand_button' ) ),
'dbProps' => array(  ),
'version' => 14,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'listTotals' => 1 );
		?>