<?php
			$optionsArray = array( 'totals' => array( 'cuentasalma_id' => array( 'totalsType' => '' ),
'ca_codcuentat' => array( 'totalsType' => '' ),
'ca_codcuenta' => array( 'totalsType' => '' ),
'ca_nomcuenta' => array( 'totalsType' => '' ),
'nombrecuenta' => array( 'totalsType' => '' ),
'ca_recibemovto' => array( 'totalsType' => '' ),
'ca_tipocuenta' => array( 'totalsType' => '' ),
'geusuario' => array( 'totalsType' => '' ),
'gefechaactua' => array( 'totalsType' => '' ),
'tac_vidautil' => array( 'totalsType' => '' ),
'tac_codcta' => array( 'totalsType' => '' ),
'nicsp_cuentacostocod' => array( 'totalsType' => '' ),
'nicsp_cuentacostonam' => array( 'totalsType' => '' ),
'nicsp_cuentadepcod' => array( 'totalsType' => '' ),
'nicsp_cuentadepname' => array( 'totalsType' => '' ),
'nicsp_cuentacostonew' => array( 'totalsType' => '' ),
'nicsp_cuentacostoservicio' => array( 'totalsType' => '' ),
'nicsp_cuentacostocodnopp' => array( 'totalsType' => '' ),
'nicsp_comodato_entrega' => array( 'totalsType' => '' ),
'nicsp_comodato_recibe' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array( 'ca_codcuenta',
'ca_nomcuenta',
'ca_recibemovto',
'tac_vidautil',
'tac_codcta',
'nicsp_cuentadepcod',
'nicsp_cuentacostonew',
'nicsp_cuentacostoservicio',
'nicsp_cuentacostocodnopp',
'nombrecuenta' ),
'exportFields' => array( 'ca_codcuenta',
'ca_nomcuenta',
'ca_recibemovto',
'tac_vidautil',
'tac_codcta',
'nicsp_cuentadepcod',
'nicsp_cuentacostonew',
'nicsp_cuentacostoservicio',
'nicsp_cuentacostocodnopp',
'nombrecuenta' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'ca_codcuenta' => array( 'export_field2' ),
'ca_nomcuenta' => array( 'export_field3' ),
'ca_recibemovto' => array( 'export_field4' ),
'tac_vidautil' => array( 'export_field8' ),
'tac_codcta' => array( 'export_field9' ),
'nicsp_cuentadepcod' => array( 'export_field12' ),
'nicsp_cuentacostonew' => array( 'export_field14' ),
'nicsp_cuentacostoservicio' => array( 'export_field15' ),
'nicsp_cuentacostocodnopp' => array( 'export_field16' ),
'nombrecuenta' => array( 'export_field' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'export_header' ),
'grid' => array( 'export_field2',
'export_field3',
'export_field4',
'export_field8',
'export_field9',
'export_field12',
'export_field14',
'export_field15',
'export_field16',
'export_field' ),
'footer' => array( 'export_export',
'export_cancel' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'export_header' => 'top',
'export_field2' => 'grid',
'export_field3' => 'grid',
'export_field4' => 'grid',
'export_field8' => 'grid',
'export_field9' => 'grid',
'export_field12' => 'grid',
'export_field14' => 'grid',
'export_field15' => 'grid',
'export_field16' => 'grid',
'export_field' => 'grid',
'export_export' => 'footer',
'export_cancel' => 'footer' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'export_header' => array( 'export_header' ),
'export_export' => array( 'export_export' ),
'export_cancel' => array( 'export_cancel' ),
'export_field' => array( 'export_field2',
'export_field3',
'export_field4',
'export_field8',
'export_field9',
'export_field12',
'export_field14',
'export_field15',
'export_field16',
'export_field' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false,
'menus' => array(  ),
'calcTotalsFor' => 1 ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'export' => array( 'format' => 2,
'selectFields' => false,
'delimiter' => ',',
'selectDelimiter' => false,
'exportFileTypes' => array( 'excel' => true,
'word' => true,
'csv' => true,
'xml' => false ) ) );
			$pageArray = array( 'id' => 'export',
'type' => 'export',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'export-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_header' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'export-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_field2',
'export_field3',
'export_field4',
'export_field8',
'export_field9',
'export_field12',
'export_field14',
'export_field15',
'export_field16',
'export_field' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'footer' => array( 'modelId' => 'export-footer',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ),
'c2' => array( 'model' => 'c2',
'items' => array( 'export_export',
'export_cancel' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'export_header' => array( 'type' => 'export_header' ),
'export_export' => array( 'type' => 'export_export' ),
'export_cancel' => array( 'type' => 'export_cancel' ),
'export_field2' => array( 'field' => 'ca_codcuenta',
'type' => 'export_field' ),
'export_field3' => array( 'field' => 'ca_nomcuenta',
'type' => 'export_field' ),
'export_field4' => array( 'field' => 'ca_recibemovto',
'type' => 'export_field' ),
'export_field8' => array( 'field' => 'tac_vidautil',
'type' => 'export_field' ),
'export_field9' => array( 'field' => 'tac_codcta',
'type' => 'export_field' ),
'export_field12' => array( 'field' => 'nicsp_cuentadepcod',
'type' => 'export_field' ),
'export_field14' => array( 'field' => 'nicsp_cuentacostonew',
'type' => 'export_field' ),
'export_field15' => array( 'field' => 'nicsp_cuentacostoservicio',
'type' => 'export_field' ),
'export_field16' => array( 'field' => 'nicsp_cuentacostocodnopp',
'type' => 'export_field' ),
'export_field' => array( 'field' => 'nombrecuenta',
'type' => 'export_field' ) ),
'dbProps' => array(  ),
'version' => 14,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'listTotals' => 1,
'exportFormat' => 2,
'exportDelimiter' => ',',
'exportSelectDelimiter' => false,
'exportSelectFields' => false );
		?>