<?php
			$optionsArray = array( 'details' => array( 'aldevindiv_sol_vinc_sign' => array( 'displayPreview' => 2,
'previewPageId' => '' ) ),
'captcha' => array( 'captcha' => false ),
'fields' => array( 'gridFields' => array( 'sign_b_hash_v',
'sign_a_user',
'sign_a_documento',
'sign_a_email',
'sign_b_user',
'sign_b_documento',
'sign_b_email',
'sign_a_hash',
'sign_b_hash',
'sign_b_hash_v_date',
'sign_b_hash_v_ip',
'sol_rad' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'updateOnEditFields' => array(  ),
'fieldItems' => array( 'sign_b_hash_v' => array( 'integrated_edit_field3',
'edit_field_label1',
'edit_field_tooltip1' ),
'sign_a_user' => array( 'integrated_edit_field1' ),
'sign_a_documento' => array( 'integrated_edit_field2' ),
'sign_a_email' => array( 'integrated_edit_field4' ),
'sign_b_user' => array( 'integrated_edit_field5' ),
'sign_b_documento' => array( 'integrated_edit_field6' ),
'sign_b_email' => array( 'integrated_edit_field7' ),
'sign_a_hash' => array( 'integrated_edit_field8' ),
'sign_b_hash' => array( 'integrated_edit_field9' ),
'sign_b_hash_v_date' => array( 'integrated_edit_field12' ),
'sign_b_hash_v_ip' => array( 'integrated_edit_field13' ),
'sol_rad' => array( 'integrated_edit_field',
'edit_field_label' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => true,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'above-grid' => array( 'edit_message' ),
'below-grid' => array( 'edit_save',
'edit_back_list',
'edit_close',
'hamburger' ),
'supertop' => array( 'expand_menu_button',
'collapse_button',
'loginform_login',
'username_button' ),
'left' => array( 'logo',
'expand_button',
'menu' ),
'top' => array( 'edit_header' ),
'grid' => array( 'tabs' ),
'section' => array( 'integrated_edit_field5',
'integrated_edit_field6',
'integrated_edit_field1',
'integrated_edit_field2',
'integrated_edit_field4',
'integrated_edit_field7',
'integrated_edit_field12',
'integrated_edit_field13',
'edit_field_label1',
'integrated_edit_field3',
'edit_field_tooltip1',
'edit_field_label',
'integrated_edit_field' ),
'section1' => array( 'integrated_edit_field8',
'integrated_edit_field9' ) ),
'formXtTags' => array( 'above-grid' => array( 'message_block' ) ),
'itemForms' => array( 'edit_message' => 'above-grid',
'edit_save' => 'below-grid',
'edit_back_list' => 'below-grid',
'edit_close' => 'below-grid',
'hamburger' => 'below-grid',
'expand_menu_button' => 'supertop',
'collapse_button' => 'supertop',
'loginform_login' => 'supertop',
'username_button' => 'supertop',
'logo' => 'left',
'expand_button' => 'left',
'menu' => 'left',
'edit_header' => 'top',
'tabs' => 'grid',
'integrated_edit_field5' => 'section',
'integrated_edit_field6' => 'section',
'integrated_edit_field1' => 'section',
'integrated_edit_field2' => 'section',
'integrated_edit_field4' => 'section',
'integrated_edit_field7' => 'section',
'integrated_edit_field12' => 'section',
'integrated_edit_field13' => 'section',
'edit_field_label1' => 'section',
'integrated_edit_field3' => 'section',
'edit_field_tooltip1' => 'section',
'edit_field_label' => 'section',
'integrated_edit_field' => 'section',
'integrated_edit_field8' => 'section1',
'integrated_edit_field9' => 'section1' ),
'itemLocations' => array( 'tabs' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field5' => array( 'location' => 'section',
'cellId' => 'c1' ),
'integrated_edit_field6' => array( 'location' => 'section',
'cellId' => 'c' ),
'integrated_edit_field1' => array( 'location' => 'section',
'cellId' => 'c2' ),
'integrated_edit_field2' => array( 'location' => 'section',
'cellId' => 'c3' ),
'integrated_edit_field4' => array( 'location' => 'section',
'cellId' => 'c4' ),
'integrated_edit_field7' => array( 'location' => 'section',
'cellId' => 'c5' ),
'integrated_edit_field12' => array( 'location' => 'section',
'cellId' => 'c13' ),
'integrated_edit_field13' => array( 'location' => 'section',
'cellId' => 'c14' ),
'edit_field_label1' => array( 'location' => 'section',
'cellId' => 'c16' ),
'integrated_edit_field3' => array( 'location' => 'section',
'cellId' => 'c16' ),
'edit_field_tooltip1' => array( 'location' => 'section',
'cellId' => 'c16' ),
'edit_field_label' => array( 'location' => 'section',
'cellId' => 'c6' ),
'integrated_edit_field' => array( 'location' => 'section',
'cellId' => 'c7' ),
'integrated_edit_field8' => array( 'location' => 'section1',
'cellId' => 'c1' ),
'integrated_edit_field9' => array( 'location' => 'section1',
'cellId' => 'c' ) ),
'itemVisiblity' => array( 'expand_menu_button' => 2,
'expand_button' => 5 ) ),
'itemsByType' => array( 'edit_header' => array( 'edit_header' ),
'edit_message' => array( 'edit_message' ),
'edit_save' => array( 'edit_save' ),
'edit_back_list' => array( 'edit_back_list' ),
'edit_close' => array( 'edit_close' ),
'hamburger' => array( 'hamburger' ),
'edit_reset' => array( 'edit_reset' ),
'edit_view' => array( 'edit_view' ),
'edit_field' => array( 'integrated_edit_field3',
'integrated_edit_field8',
'integrated_edit_field9',
'integrated_edit_field' ),
'logo' => array( 'logo' ),
'menu' => array( 'menu' ),
'username_button' => array( 'username_button' ),
'loginform_login' => array( 'loginform_login' ),
'userinfo_link' => array( 'userinfo_link' ),
'logout_link' => array( 'logout_link' ),
'expand_menu_button' => array( 'expand_menu_button' ),
'collapse_button' => array( 'collapse_button' ),
'integrated_edit_field' => array( 'integrated_edit_field1',
'integrated_edit_field2',
'integrated_edit_field4',
'integrated_edit_field5',
'integrated_edit_field6',
'integrated_edit_field7',
'integrated_edit_field12',
'integrated_edit_field13' ),
'tabs' => array( 'tabs' ),
'edit_field_label' => array( 'edit_field_label1',
'edit_field_label' ),
'edit_field_tooltip' => array( 'edit_field_tooltip1' ),
'expand_button' => array( 'expand_button' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'c3' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'tabs' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 1 ),
'section' => array( 'cells' => array( 'c6' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array( 'sol_rad_fieldblock' ),
'items' => array( 'edit_field_label' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c7' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c8' => array( 'cols' => array( 2 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c2' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field1' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c3' => array( 'cols' => array( 1 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field2' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c4' => array( 'cols' => array( 2 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field4' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c1' => array( 'cols' => array( 0 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field5' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 1 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field6' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c5' => array( 'cols' => array( 2 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field7' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c16' => array( 'cols' => array( 0,
1,
2 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array( 'edit_field_label1',
'integrated_edit_field3',
'edit_field_tooltip1' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c13' => array( 'cols' => array( 0 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field12' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c14' => array( 'cols' => array( 1 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field13' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c15' => array( 'cols' => array( 2 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ) ),
'width' => 3,
'height' => 5 ),
'section1' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field8' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field9' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 2 ) ) ),
'loginForm' => array( 'loginForm' => 0 ),
'page' => array( 'verticalBar' => true,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false,
'menus' => array( array( 'id' => 'main',
'horizontal' => false ) ),
'calcTotalsFor' => 1 ),
'misc' => array( 'type' => 'edit',
'breadcrumb' => false,
'nextPrev' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'edit' => array( 'updateSelected' => false ) );
			$pageArray = array( 'id' => 'edit',
'type' => 'edit',
'layoutId' => 'leftbar',
'disabled' => 0,
'default' => 0,
'forms' => array( 'above-grid' => array( 'modelId' => 'edit-above-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'edit_message' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'edit-below-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'edit_save',
'edit_back_list',
'edit_close' ) ),
'c2' => array( 'model' => 'c2',
'items' => array( 'hamburger' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'supertop' => array( 'modelId' => 'leftbar-top-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'expand_menu_button',
'collapse_button' ) ),
'c2' => array( 'model' => 'c2',
'items' => array( 'loginform_login',
'username_button' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'left' => array( 'modelId' => 'leftbar-menu',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c0' ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c0' => array( 'model' => 'c0',
'items' => array( 'logo',
'expand_button' ) ),
'c1' => array( 'model' => 'c1',
'items' => array( 'menu' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'edit-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'edit_header' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c3',
'colspan' => 1 ) ),
'section' => '' ) ),
'cells' => array( 'c3' => array( 'model' => 'c3',
'items' => array( 'tabs' ),
'useFullWidth' => true ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'section' => '',
'cells' => array( array( 'cell' => 'c6' ),
array( 'cell' => 'c7' ),
array( 'cell' => 'c8' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c2' ),
array( 'cell' => 'c3' ),
array( 'cell' => 'c4' ) ) ),
array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c' ),
array( 'cell' => 'c5' ) ),
'section' => '' ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c16',
'colspan' => 3 ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c13' ),
array( 'cell' => 'c14' ),
array( 'cell' => 'c15' ) ) ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field5' ) ),
'c' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field6' ) ),
'c2' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field1' ) ),
'c3' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field2' ) ),
'c4' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field4' ) ),
'c5' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field7' ) ),
'c13' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field12' ) ),
'c14' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field13' ) ),
'c15' => array( 'model' => 'c1',
'items' => array(  ) ),
'c16' => array( 'model' => 'c3',
'items' => array( 'edit_field_label1',
'integrated_edit_field3',
'edit_field_tooltip1' ) ),
'c6' => array( 'model' => 'c3',
'items' => array( 'edit_field_label' ) ),
'c7' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field' ) ),
'c8' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section1' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c' ) ) ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field8' ) ),
'c' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field9' ) ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ) ),
'items' => array( 'edit_header' => array( 'type' => 'edit_header',
'title' => array( 'page' => 'edit',
'table' => 'aldevindiv_sol_sign_b',
'type' => 7 ),
'font-family' => 'Roboto' ),
'edit_message' => array( 'type' => 'edit_message' ),
'edit_save' => array( 'type' => 'edit_save',
'label' => array( 'type' => 0,
'text' => 'Firmar documento' ),
'icon' => array( 'fa' => 'qrcode' ),
'buttonStyle' => 'success',
'buttonSize' => 'large' ),
'edit_back_list' => array( 'type' => 'edit_back_list',
'buttonSize' => 'large',
'label' => array( 'type' => 0,
'text' => 'Regresar' ) ),
'edit_close' => array( 'type' => 'edit_close' ),
'hamburger' => array( 'type' => 'hamburger',
'items' => array( 'edit_reset',
'edit_view' ) ),
'edit_reset' => array( 'type' => 'edit_reset' ),
'edit_view' => array( 'type' => 'edit_view' ),
'integrated_edit_field3' => array( 'field' => 'sign_b_hash_v',
'type' => 'edit_field',
'orientation' => 0,
'joined' => false,
'separated' => true,
'font-family' => 'Roboto',
'bold' => true,
'font-size' => '20px' ),
'logo' => array( 'type' => 'logo' ),
'menu' => array( 'type' => 'menu' ),
'username_button' => array( 'type' => 'username_button',
'items' => array( 'userinfo_link',
'logout_link' ) ),
'loginform_login' => array( 'type' => 'loginform_login' ),
'userinfo_link' => array( 'type' => 'userinfo_link' ),
'logout_link' => array( 'type' => 'logout_link' ),
'expand_menu_button' => array( 'type' => 'expand_menu_button' ),
'collapse_button' => array( 'type' => 'collapse_button' ),
'integrated_edit_field1' => array( 'field' => 'sign_a_user',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field2' => array( 'field' => 'sign_a_documento',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field4' => array( 'field' => 'sign_a_email',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field5' => array( 'field' => 'sign_b_user',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field6' => array( 'field' => 'sign_b_documento',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field7' => array( 'field' => 'sign_b_email',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field8' => array( 'field' => 'sign_a_hash',
'type' => 'edit_field',
'orientation' => 0,
'updateOnEdit' => false,
'joined' => false,
'separated' => true ),
'integrated_edit_field9' => array( 'field' => 'sign_b_hash',
'type' => 'edit_field',
'orientation' => 0,
'updateOnEdit' => false,
'joined' => false,
'separated' => true ),
'tabs' => array( 'type' => 'tabs',
'titles' => array( array( 'text' => 'Generar token de firma',
'type' => 0 ),
array( 'text' => '',
'type' => 0 ) ),
'locations' => array( 'section',
'section1' ),
'bsStyle' => 'default',
'panelType' => 2 ),
'integrated_edit_field12' => array( 'field' => 'sign_b_hash_v_date',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field13' => array( 'field' => 'sign_b_hash_v_ip',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'edit_field_label1' => array( 'type' => 'edit_field_label',
'field' => 'sign_b_hash_v',
'separated' => true ),
'edit_field_tooltip1' => array( 'type' => 'edit_field_tooltip',
'field' => 'sign_b_hash_v',
'separated' => true,
'tooltip' => array( 'field' => 'sign_b_hash_v',
'table' => null,
'type' => 4 ) ),
'integrated_edit_field' => array( 'field' => 'sol_rad',
'type' => 'edit_field',
'orientation' => 0,
'joined' => false,
'separated' => true,
'font-family' => 'Roboto',
'font-size' => '18px',
'bold' => true,
'updateOnEdit' => false ),
'edit_field_label' => array( 'type' => 'edit_field_label',
'field' => 'sol_rad',
'separated' => true ),
'expand_button' => array( 'type' => 'expand_button' ) ),
'dbProps' => array(  ),
'version' => 14,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'listTotals' => 1 );
		?>