<?php
			$optionsArray = array( 'pdf' => array( 'pdfView' => true,
'orientation' => 'portrait',
'scale' => 100 ),
'details' => array( 'aldevindiv_sol_vinc_sign' => array( 'displayPreview' => 1 ) ),
'totals' => array( 'transact_id' => array( 'totalsType' => '' ),
'username_id' => array( 'totalsType' => '' ),
'sol_rad' => array( 'totalsType' => '' ),
'sol_estado' => array( 'totalsType' => '' ),
'sol_userfr' => array( 'totalsType' => '' ),
'sol_userid' => array( 'totalsType' => '' ),
'sol_userto' => array( 'totalsType' => '' ),
'sol_fecha' => array( 'totalsType' => '' ),
'sol_mailnot' => array( 'totalsType' => '' ),
'sol_type' => array( 'totalsType' => '' ),
'usr_fecha' => array( 'totalsType' => '' ),
'usr_username' => array( 'totalsType' => '' ),
'sol_obs' => array( 'totalsType' => '' ),
'sign_a_user' => array( 'totalsType' => '' ),
'sign_a_documento' => array( 'totalsType' => '' ),
'sign_a_email' => array( 'totalsType' => '' ),
'sign_b_user' => array( 'totalsType' => '' ),
'sign_b_documento' => array( 'totalsType' => '' ),
'sign_b_email' => array( 'totalsType' => '' ),
'sign_a_hash' => array( 'totalsType' => '' ),
'sign_b_hash' => array( 'totalsType' => '' ),
'sign_a_qr' => array( 'totalsType' => '' ),
'sign_b_qr' => array( 'totalsType' => '' ),
'sign_a_hash_v' => array( 'totalsType' => '' ),
'sign_a_hash_v_date' => array( 'totalsType' => '' ),
'sign_a_hash_v_ip' => array( 'totalsType' => '' ),
'sign_b_hash_v' => array( 'totalsType' => '' ),
'sign_b_hash_v_date' => array( 'totalsType' => '' ),
'sign_b_hash_v_ip' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array( 'sol_estado',
'sol_fecha',
'sol_rad',
'sol_type',
'sol_userfr',
'sol_userto',
'transact_id',
'username_id',
'sign_a_hash_v',
'sign_a_hash_v_date',
'sign_a_user',
'sign_a_documento',
'sign_a_email',
'sign_b_user',
'sign_b_documento',
'sign_b_email',
'sign_a_hash_v_ip',
'sign_b_hash_v',
'sign_b_hash_v_date',
'sign_b_hash_v_ip' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'sol_estado' => array( 'simple_grid_field',
'simple_grid_field3' ),
'sol_fecha' => array( 'simple_grid_field1',
'simple_grid_field2' ),
'sol_rad' => array( 'simple_grid_field4',
'simple_grid_field7' ),
'sol_type' => array( 'simple_grid_field5',
'simple_grid_field12' ),
'sol_userfr' => array( 'simple_grid_field6',
'simple_grid_field13' ),
'sol_userto' => array( 'simple_grid_field8',
'simple_grid_field14' ),
'transact_id' => array( 'simple_grid_field9',
'simple_grid_field15' ),
'username_id' => array( 'simple_grid_field10',
'simple_grid_field11' ),
'sign_a_hash_v' => array( 'grid_field',
'grid_field_label' ),
'sign_a_hash_v_date' => array( 'grid_field1',
'grid_field_label1' ),
'sign_a_user' => array( 'grid_field2',
'grid_field_label2' ),
'sign_a_documento' => array( 'grid_field3',
'grid_field_label3' ),
'sign_a_email' => array( 'grid_field4',
'grid_field_label4' ),
'sign_b_user' => array( 'grid_field5',
'grid_field_label5' ),
'sign_b_documento' => array( 'grid_field6',
'grid_field_label6' ),
'sign_b_email' => array( 'grid_field7',
'grid_field_label7' ),
'sign_a_hash_v_ip' => array( 'grid_field8',
'grid_field_label8' ),
'sign_b_hash_v' => array( 'grid_field9',
'grid_field_label9' ),
'sign_b_hash_v_date' => array( 'grid_field10',
'grid_field_label10' ),
'sign_b_hash_v_ip' => array( 'grid_field11',
'grid_field_label11' ) ),
'hideEmptyFields' => array(  ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'above-grid' => array( 'print_pages' ),
'below-grid' => array(  ),
'top' => array( 'print_header',
'print_subheader',
'print_pdf',
'image' ),
'grid' => array( 'simple_grid_field7',
'simple_grid_field4',
'simple_grid_field2',
'simple_grid_field1',
'simple_grid_field11',
'simple_grid_field10',
'simple_grid_field3',
'simple_grid_field',
'simple_grid_field12',
'simple_grid_field5',
'simple_grid_field13',
'simple_grid_field6',
'simple_grid_field14',
'simple_grid_field8',
'simple_grid_field15',
'simple_grid_field9',
'grid_field_label5',
'details_preview',
'grid_field_label2',
'grid_field_label1',
'grid_field_label',
'grid_field',
'grid_field_label4',
'grid_field4',
'grid_field_label3',
'grid_field3',
'grid_field_label6',
'grid_field6',
'grid_field_label7',
'grid_field7',
'grid_field5',
'grid_field2',
'grid_field1',
'grid_field_label8',
'grid_field8',
'grid_field_label9',
'grid_field9',
'grid_field_label10',
'grid_field10',
'grid_field_label11',
'grid_field11' ) ),
'formXtTags' => array( 'above-grid' => array( 'print_pages' ),
'below-grid' => array(  ) ),
'itemForms' => array( 'print_pages' => 'above-grid',
'print_header' => 'top',
'print_subheader' => 'top',
'print_pdf' => 'top',
'image' => 'top',
'simple_grid_field7' => 'grid',
'simple_grid_field4' => 'grid',
'simple_grid_field2' => 'grid',
'simple_grid_field1' => 'grid',
'simple_grid_field11' => 'grid',
'simple_grid_field10' => 'grid',
'simple_grid_field3' => 'grid',
'simple_grid_field' => 'grid',
'simple_grid_field12' => 'grid',
'simple_grid_field5' => 'grid',
'simple_grid_field13' => 'grid',
'simple_grid_field6' => 'grid',
'simple_grid_field14' => 'grid',
'simple_grid_field8' => 'grid',
'simple_grid_field15' => 'grid',
'simple_grid_field9' => 'grid',
'grid_field_label5' => 'grid',
'details_preview' => 'grid',
'grid_field_label2' => 'grid',
'grid_field_label1' => 'grid',
'grid_field_label' => 'grid',
'grid_field' => 'grid',
'grid_field_label4' => 'grid',
'grid_field4' => 'grid',
'grid_field_label3' => 'grid',
'grid_field3' => 'grid',
'grid_field_label6' => 'grid',
'grid_field6' => 'grid',
'grid_field_label7' => 'grid',
'grid_field7' => 'grid',
'grid_field5' => 'grid',
'grid_field2' => 'grid',
'grid_field1' => 'grid',
'grid_field_label8' => 'grid',
'grid_field8' => 'grid',
'grid_field_label9' => 'grid',
'grid_field9' => 'grid',
'grid_field_label10' => 'grid',
'grid_field10' => 'grid',
'grid_field_label11' => 'grid',
'grid_field11' => 'grid' ),
'itemLocations' => array( 'simple_grid_field7' => array( 'location' => 'grid',
'cellId' => 'headcell_field' ),
'simple_grid_field4' => array( 'location' => 'grid',
'cellId' => 'cell_field' ),
'simple_grid_field2' => array( 'location' => 'grid',
'cellId' => 'headcell_field1' ),
'simple_grid_field1' => array( 'location' => 'grid',
'cellId' => 'cell_field1' ),
'simple_grid_field11' => array( 'location' => 'grid',
'cellId' => 'headcell_field2' ),
'simple_grid_field10' => array( 'location' => 'grid',
'cellId' => 'cell_field2' ),
'simple_grid_field3' => array( 'location' => 'grid',
'cellId' => 'headcell_field3' ),
'simple_grid_field' => array( 'location' => 'grid',
'cellId' => 'cell_field3' ),
'simple_grid_field12' => array( 'location' => 'grid',
'cellId' => 'headcell_field4' ),
'simple_grid_field5' => array( 'location' => 'grid',
'cellId' => 'cell_field4' ),
'simple_grid_field13' => array( 'location' => 'grid',
'cellId' => 'headcell_field5' ),
'simple_grid_field6' => array( 'location' => 'grid',
'cellId' => 'cell_field5' ),
'simple_grid_field14' => array( 'location' => 'grid',
'cellId' => 'headcell_field6' ),
'simple_grid_field8' => array( 'location' => 'grid',
'cellId' => 'cell_field6' ),
'simple_grid_field15' => array( 'location' => 'grid',
'cellId' => 'headcell_field7' ),
'simple_grid_field9' => array( 'location' => 'grid',
'cellId' => 'cell_field7' ),
'grid_field_label5' => array( 'location' => 'grid',
'cellId' => 'cell_dpreview5' ),
'details_preview' => array( 'location' => 'grid',
'cellId' => 'cell_dpreview5' ),
'grid_field_label2' => array( 'location' => 'grid',
'cellId' => 'cell_dpreview4' ),
'grid_field_label1' => array( 'location' => 'grid',
'cellId' => 'headcell_field9' ),
'grid_field_label' => array( 'location' => 'grid',
'cellId' => 'headcell_field8' ),
'grid_field' => array( 'location' => 'grid',
'cellId' => 'cell_field8' ),
'grid_field_label4' => array( 'location' => 'grid',
'cellId' => 'cell_dpreview6' ),
'grid_field4' => array( 'location' => 'grid',
'cellId' => 'cell_dpreview6' ),
'grid_field_label3' => array( 'location' => 'grid',
'cellId' => 'cell_dpreview7' ),
'grid_field3' => array( 'location' => 'grid',
'cellId' => 'cell_dpreview7' ),
'grid_field_label6' => array( 'location' => 'grid',
'cellId' => 'cell_dpreview8' ),
'grid_field6' => array( 'location' => 'grid',
'cellId' => 'cell_dpreview8' ),
'grid_field_label7' => array( 'location' => 'grid',
'cellId' => 'cell_dpreview9' ),
'grid_field7' => array( 'location' => 'grid',
'cellId' => 'cell_dpreview9' ),
'grid_field5' => array( 'location' => 'grid',
'cellId' => 'cell_dpreview10' ),
'grid_field2' => array( 'location' => 'grid',
'cellId' => 'cell_dpreview11' ),
'grid_field1' => array( 'location' => 'grid',
'cellId' => 'cell_field43' ),
'grid_field_label8' => array( 'location' => 'grid',
'cellId' => 'headcell_field16' ),
'grid_field8' => array( 'location' => 'grid',
'cellId' => 'cell_field48' ),
'grid_field_label9' => array( 'location' => 'grid',
'cellId' => 'headcell_field17' ),
'grid_field9' => array( 'location' => 'grid',
'cellId' => 'cell_field53' ),
'grid_field_label10' => array( 'location' => 'grid',
'cellId' => 'headcell_field18' ),
'grid_field10' => array( 'location' => 'grid',
'cellId' => 'cell_field58' ),
'grid_field_label11' => array( 'location' => 'grid',
'cellId' => 'headcell_field19' ),
'grid_field11' => array( 'location' => 'grid',
'cellId' => 'cell_field63' ) ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'print_header' => array( 'print_header' ),
'print_subheader' => array( 'print_subheader' ),
'print_pages' => array( 'print_pages' ),
'grid_field' => array( 'simple_grid_field',
'simple_grid_field1',
'simple_grid_field4',
'simple_grid_field5',
'simple_grid_field6',
'simple_grid_field8',
'simple_grid_field9',
'simple_grid_field10',
'grid_field',
'grid_field1',
'grid_field2',
'grid_field3',
'grid_field4',
'grid_field5',
'grid_field6',
'grid_field7',
'grid_field8',
'grid_field9',
'grid_field10',
'grid_field11' ),
'grid_field_label' => array( 'simple_grid_field2',
'simple_grid_field3',
'simple_grid_field7',
'simple_grid_field11',
'simple_grid_field12',
'simple_grid_field13',
'simple_grid_field14',
'simple_grid_field15',
'grid_field_label',
'grid_field_label1',
'grid_field_label2',
'grid_field_label3',
'grid_field_label4',
'grid_field_label5',
'grid_field_label6',
'grid_field_label7',
'grid_field_label8',
'grid_field_label9',
'grid_field_label10',
'grid_field_label11' ),
'details_preview' => array( 'details_preview' ),
'print_pdf' => array( 'print_pdf' ),
'image' => array( 'image' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'headcell_field' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array( 'sol_rad_fieldheadercolumn' ),
'items' => array( 'simple_grid_field7' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field1' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array( 'sol_fecha_fieldheadercolumn' ),
'items' => array( 'simple_grid_field2' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field2' => array( 'cols' => array( 2 ),
'rows' => array( 0 ),
'tags' => array( 'username_id_fieldheadercolumn' ),
'items' => array( 'simple_grid_field11' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field3' => array( 'cols' => array( 3 ),
'rows' => array( 0 ),
'tags' => array( 'sol_estado_fieldheadercolumn' ),
'items' => array( 'simple_grid_field3' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field4' => array( 'cols' => array( 4 ),
'rows' => array( 0 ),
'tags' => array( 'sol_type_fieldheadercolumn' ),
'items' => array( 'simple_grid_field12' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field5' => array( 'cols' => array( 5 ),
'rows' => array( 0 ),
'tags' => array( 'sol_userfr_fieldheadercolumn' ),
'items' => array( 'simple_grid_field13' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field6' => array( 'cols' => array( 6 ),
'rows' => array( 0 ),
'tags' => array( 'sol_userto_fieldheadercolumn' ),
'items' => array( 'simple_grid_field14' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field7' => array( 'cols' => array( 7 ),
'rows' => array( 0 ),
'tags' => array( 'transact_id_fieldheadercolumn' ),
'items' => array( 'simple_grid_field15' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field10' => array( 'cols' => array( 8 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field11' => array( 'cols' => array( 9 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field12' => array( 'cols' => array( 10 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field13' => array( 'cols' => array( 11 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field14' => array( 'cols' => array( 12 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field15' => array( 'cols' => array( 13 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field8' => array( 'cols' => array( 14 ),
'rows' => array( 0 ),
'tags' => array( 'sign_a_hash_v_fieldheadercolumn' ),
'items' => array( 'grid_field_label' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field9' => array( 'cols' => array( 15 ),
'rows' => array( 0 ),
'tags' => array( 'sign_a_hash_v_date_fieldheadercolumn' ),
'items' => array( 'grid_field_label1' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field16' => array( 'cols' => array( 16 ),
'rows' => array( 0 ),
'tags' => array( 'sign_a_hash_v_ip_fieldheadercolumn' ),
'items' => array( 'grid_field_label8' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field17' => array( 'cols' => array( 17 ),
'rows' => array( 0 ),
'tags' => array( 'sign_b_hash_v_fieldheadercolumn' ),
'items' => array( 'grid_field_label9' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field18' => array( 'cols' => array( 18 ),
'rows' => array( 0 ),
'tags' => array( 'sign_b_hash_v_date_fieldheadercolumn' ),
'items' => array( 'grid_field_label10' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field19' => array( 'cols' => array( 19 ),
'rows' => array( 0 ),
'tags' => array( 'sign_b_hash_v_ip_fieldheadercolumn' ),
'items' => array( 'grid_field_label11' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array( 'sol_rad_fieldcolumn' ),
'items' => array( 'simple_grid_field4' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field1' => array( 'cols' => array( 1 ),
'rows' => array( 1 ),
'tags' => array( 'sol_fecha_fieldcolumn' ),
'items' => array( 'simple_grid_field1' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field2' => array( 'cols' => array( 2 ),
'rows' => array( 1 ),
'tags' => array( 'username_id_fieldcolumn' ),
'items' => array( 'simple_grid_field10' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field3' => array( 'cols' => array( 3 ),
'rows' => array( 1 ),
'tags' => array( 'sol_estado_fieldcolumn' ),
'items' => array( 'simple_grid_field' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field4' => array( 'cols' => array( 4 ),
'rows' => array( 1 ),
'tags' => array( 'sol_type_fieldcolumn' ),
'items' => array( 'simple_grid_field5' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field5' => array( 'cols' => array( 5 ),
'rows' => array( 1 ),
'tags' => array( 'sol_userfr_fieldcolumn' ),
'items' => array( 'simple_grid_field6' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field6' => array( 'cols' => array( 6 ),
'rows' => array( 1 ),
'tags' => array( 'sol_userto_fieldcolumn' ),
'items' => array( 'simple_grid_field8' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field7' => array( 'cols' => array( 7 ),
'rows' => array( 1 ),
'tags' => array( 'transact_id_fieldcolumn' ),
'items' => array( 'simple_grid_field9' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field10' => array( 'cols' => array( 8 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field15' => array( 'cols' => array( 9 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field20' => array( 'cols' => array( 10 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field25' => array( 'cols' => array( 11 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field30' => array( 'cols' => array( 12 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field35' => array( 'cols' => array( 13 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field8' => array( 'cols' => array( 14 ),
'rows' => array( 1 ),
'tags' => array( 'sign_a_hash_v_fieldcolumn' ),
'items' => array( 'grid_field' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field43' => array( 'cols' => array( 15 ),
'rows' => array( 1 ),
'tags' => array( 'sign_a_hash_v_date_fieldcolumn' ),
'items' => array( 'grid_field1' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field48' => array( 'cols' => array( 16 ),
'rows' => array( 1 ),
'tags' => array( 'sign_a_hash_v_ip_fieldcolumn' ),
'items' => array( 'grid_field8' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field53' => array( 'cols' => array( 17 ),
'rows' => array( 1 ),
'tags' => array( 'sign_b_hash_v_fieldcolumn' ),
'items' => array( 'grid_field9' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field58' => array( 'cols' => array( 18 ),
'rows' => array( 1 ),
'tags' => array( 'sign_b_hash_v_date_fieldcolumn' ),
'items' => array( 'grid_field10' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field63' => array( 'cols' => array( 19 ),
'rows' => array( 1 ),
'tags' => array( 'sign_b_hash_v_ip_fieldcolumn' ),
'items' => array( 'grid_field11' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_dpreview2' => array( 'cols' => array( 0,
1,
2,
3,
4 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_dpreview3' => array( 'cols' => array( 5,
6,
7 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field11' => array( 'cols' => array( 8 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field16' => array( 'cols' => array( 9 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field21' => array( 'cols' => array( 10 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field26' => array( 'cols' => array( 11 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field31' => array( 'cols' => array( 12 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field36' => array( 'cols' => array( 13 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field9' => array( 'cols' => array( 14 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field44' => array( 'cols' => array( 15 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field49' => array( 'cols' => array( 16 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field54' => array( 'cols' => array( 17 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field59' => array( 'cols' => array( 18 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field64' => array( 'cols' => array( 19 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_dpreview4' => array( 'cols' => array( 0,
1 ),
'rows' => array( 3 ),
'tags' => array( 'sign_a_user_fieldheadercolumn' ),
'items' => array( 'grid_field_label2' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_dpreview11' => array( 'cols' => array( 2,
3,
4 ),
'rows' => array( 3 ),
'tags' => array( 'sign_a_user_fieldcolumn' ),
'items' => array( 'grid_field2' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_dpreview5' => array( 'cols' => array( 5,
6 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array( 'grid_field_label5',
'details_preview' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'cell_dpreview10' => array( 'cols' => array( 7 ),
'rows' => array( 3 ),
'tags' => array( 'sign_b_user_fieldcolumn' ),
'items' => array( 'grid_field5' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field12' => array( 'cols' => array( 8 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field17' => array( 'cols' => array( 9 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field22' => array( 'cols' => array( 10 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field27' => array( 'cols' => array( 11 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field32' => array( 'cols' => array( 12 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field37' => array( 'cols' => array( 13 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field40' => array( 'cols' => array( 14 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field45' => array( 'cols' => array( 15 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field50' => array( 'cols' => array( 16 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field55' => array( 'cols' => array( 17 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field60' => array( 'cols' => array( 18 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field65' => array( 'cols' => array( 19 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_dpreview7' => array( 'cols' => array( 0,
1,
2,
3,
4 ),
'rows' => array( 4 ),
'tags' => array( 'sign_a_documento_fieldheadercolumn',
'sign_a_documento_fieldcolumn' ),
'items' => array( 'grid_field_label3',
'grid_field3' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_dpreview8' => array( 'cols' => array( 5,
6,
7 ),
'rows' => array( 4 ),
'tags' => array( 'sign_b_documento_fieldheadercolumn',
'sign_b_documento_fieldcolumn' ),
'items' => array( 'grid_field_label6',
'grid_field6' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field13' => array( 'cols' => array( 8 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field18' => array( 'cols' => array( 9 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field23' => array( 'cols' => array( 10 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field28' => array( 'cols' => array( 11 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field33' => array( 'cols' => array( 12 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field38' => array( 'cols' => array( 13 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field41' => array( 'cols' => array( 14 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field46' => array( 'cols' => array( 15 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field51' => array( 'cols' => array( 16 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field56' => array( 'cols' => array( 17 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field61' => array( 'cols' => array( 18 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field66' => array( 'cols' => array( 19 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_dpreview6' => array( 'cols' => array( 0,
1,
2,
3,
4 ),
'rows' => array( 5 ),
'tags' => array( 'sign_a_email_fieldheadercolumn',
'sign_a_email_fieldcolumn' ),
'items' => array( 'grid_field_label4',
'grid_field4' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_dpreview9' => array( 'cols' => array( 5,
6,
7 ),
'rows' => array( 5 ),
'tags' => array( 'sign_b_email_fieldheadercolumn',
'sign_b_email_fieldcolumn' ),
'items' => array( 'grid_field_label7',
'grid_field7' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field14' => array( 'cols' => array( 8 ),
'rows' => array( 5 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field19' => array( 'cols' => array( 9 ),
'rows' => array( 5 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field24' => array( 'cols' => array( 10 ),
'rows' => array( 5 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field29' => array( 'cols' => array( 11 ),
'rows' => array( 5 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field34' => array( 'cols' => array( 12 ),
'rows' => array( 5 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field39' => array( 'cols' => array( 13 ),
'rows' => array( 5 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field42' => array( 'cols' => array( 14 ),
'rows' => array( 5 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field47' => array( 'cols' => array( 15 ),
'rows' => array( 5 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field52' => array( 'cols' => array( 16 ),
'rows' => array( 5 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field57' => array( 'cols' => array( 17 ),
'rows' => array( 5 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field62' => array( 'cols' => array( 18 ),
'rows' => array( 5 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field67' => array( 'cols' => array( 19 ),
'rows' => array( 5 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_dpreview1' => array( 'cols' => array( 0,
1,
2,
3,
4,
5,
6,
7,
8,
9,
10,
11,
12,
13,
14,
15,
16,
17,
18,
19 ),
'rows' => array( 6 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field' => array( 'cols' => array( 0 ),
'rows' => array( 7 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field1' => array( 'cols' => array( 1 ),
'rows' => array( 7 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field2' => array( 'cols' => array( 2 ),
'rows' => array( 7 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field3' => array( 'cols' => array( 3 ),
'rows' => array( 7 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field4' => array( 'cols' => array( 4 ),
'rows' => array( 7 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field5' => array( 'cols' => array( 5 ),
'rows' => array( 7 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field6' => array( 'cols' => array( 6 ),
'rows' => array( 7 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field7' => array( 'cols' => array( 7 ),
'rows' => array( 7 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field14' => array( 'cols' => array( 8 ),
'rows' => array( 7 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field16' => array( 'cols' => array( 9 ),
'rows' => array( 7 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field18' => array( 'cols' => array( 10 ),
'rows' => array( 7 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field20' => array( 'cols' => array( 11 ),
'rows' => array( 7 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field22' => array( 'cols' => array( 12 ),
'rows' => array( 7 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field24' => array( 'cols' => array( 13 ),
'rows' => array( 7 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field9' => array( 'cols' => array( 14 ),
'rows' => array( 7 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field11' => array( 'cols' => array( 15 ),
'rows' => array( 7 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field26' => array( 'cols' => array( 16 ),
'rows' => array( 7 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field28' => array( 'cols' => array( 17 ),
'rows' => array( 7 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field30' => array( 'cols' => array( 18 ),
'rows' => array( 7 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field32' => array( 'cols' => array( 19 ),
'rows' => array( 7 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field8' => array( 'cols' => array( 0,
1,
2,
3 ),
'rows' => array( 8 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field12' => array( 'cols' => array( 4,
5,
6,
7 ),
'rows' => array( 8 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field15' => array( 'cols' => array( 8 ),
'rows' => array( 8 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field17' => array( 'cols' => array( 9 ),
'rows' => array( 8 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field19' => array( 'cols' => array( 10 ),
'rows' => array( 8 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field21' => array( 'cols' => array( 11 ),
'rows' => array( 8 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field23' => array( 'cols' => array( 12 ),
'rows' => array( 8 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field25' => array( 'cols' => array( 13 ),
'rows' => array( 8 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field10' => array( 'cols' => array( 14 ),
'rows' => array( 8 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field13' => array( 'cols' => array( 15 ),
'rows' => array( 8 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field27' => array( 'cols' => array( 16 ),
'rows' => array( 8 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field29' => array( 'cols' => array( 17 ),
'rows' => array( 8 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field31' => array( 'cols' => array( 18 ),
'rows' => array( 8 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field33' => array( 'cols' => array( 19 ),
'rows' => array( 8 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ) ),
'width' => 20,
'height' => 9 ) ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array( 'print_pages' => array( 'tag' => 'PRINT_PAGES',
'type' => 2 ) ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'gridType' => 0,
'recsPerRow' => 1,
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false,
'menus' => array(  ),
'calcTotalsFor' => 1 ),
'misc' => array( 'type' => 'print',
'breadcrumb' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'dataGrid' => array( 'groupFields' => array(  ) ) );
			$pageArray = array( 'id' => 'print',
'type' => 'print',
'layoutId' => 'basic',
'disabled' => 0,
'default' => 0,
'forms' => array( 'above-grid' => array( 'modelId' => 'print-above-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'print_pages' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'print-below-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1',
'colspan' => 1 ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'print-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c' ) ) ),
array( 'cells' => array( array( 'cell' => 'c4' ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c2' => array( 'model' => 'c2',
'items' => array( 'print_header',
'print_subheader' ) ),
'c1' => array( 'model' => 'c1',
'items' => array( 'print_pdf' ) ),
'c' => array( 'model' => 'c2',
'items' => array( 'image' ) ),
'c4' => array( 'model' => 'c4',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'horizontal-grid',
'grid' => array( array( 'section' => 'head',
'cells' => array( array( 'cell' => 'headcell_field' ),
array( 'cell' => 'headcell_field1' ),
array( 'cell' => 'headcell_field2' ),
array( 'cell' => 'headcell_field3' ),
array( 'cell' => 'headcell_field4' ),
array( 'cell' => 'headcell_field5' ),
array( 'cell' => 'headcell_field6' ),
array( 'cell' => 'headcell_field7' ),
array( 'cell' => 'headcell_field10' ),
array( 'cell' => 'headcell_field11' ),
array( 'cell' => 'headcell_field12' ),
array( 'cell' => 'headcell_field13' ),
array( 'cell' => 'headcell_field14' ),
array( 'cell' => 'headcell_field15' ),
array( 'cell' => 'headcell_field8' ),
array( 'cell' => 'headcell_field9' ),
array( 'cell' => 'headcell_field16' ),
array( 'cell' => 'headcell_field17' ),
array( 'cell' => 'headcell_field18' ),
array( 'cell' => 'headcell_field19' ) ) ),
array( 'section' => 'body',
'cells' => array( array( 'cell' => 'cell_field' ),
array( 'cell' => 'cell_field1' ),
array( 'cell' => 'cell_field2' ),
array( 'cell' => 'cell_field3' ),
array( 'cell' => 'cell_field4' ),
array( 'cell' => 'cell_field5' ),
array( 'cell' => 'cell_field6' ),
array( 'cell' => 'cell_field7' ),
array( 'cell' => 'cell_field10' ),
array( 'cell' => 'cell_field15' ),
array( 'cell' => 'cell_field20' ),
array( 'cell' => 'cell_field25' ),
array( 'cell' => 'cell_field30' ),
array( 'cell' => 'cell_field35' ),
array( 'cell' => 'cell_field8' ),
array( 'cell' => 'cell_field43' ),
array( 'cell' => 'cell_field48' ),
array( 'cell' => 'cell_field53' ),
array( 'cell' => 'cell_field58' ),
array( 'cell' => 'cell_field63' ) ) ),
array( 'section' => 'body',
'cells' => array( array( 'cell' => 'cell_dpreview2',
'colspan' => 5 ),
array( 'cell' => 'cell_dpreview3',
'colspan' => 3 ),
array( 'cell' => 'cell_field11' ),
array( 'cell' => 'cell_field16' ),
array( 'cell' => 'cell_field21' ),
array( 'cell' => 'cell_field26' ),
array( 'cell' => 'cell_field31' ),
array( 'cell' => 'cell_field36' ),
array( 'cell' => 'cell_field9' ),
array( 'cell' => 'cell_field44' ),
array( 'cell' => 'cell_field49' ),
array( 'cell' => 'cell_field54' ),
array( 'cell' => 'cell_field59' ),
array( 'cell' => 'cell_field64' ) ) ),
array( 'section' => 'body',
'cells' => array( array( 'cell' => 'cell_dpreview4',
'colspan' => 2 ),
array( 'cell' => 'cell_dpreview11',
'colspan' => 3 ),
array( 'cell' => 'cell_dpreview5',
'colspan' => 2 ),
array( 'cell' => 'cell_dpreview10' ),
array( 'cell' => 'cell_field12' ),
array( 'cell' => 'cell_field17' ),
array( 'cell' => 'cell_field22' ),
array( 'cell' => 'cell_field27' ),
array( 'cell' => 'cell_field32' ),
array( 'cell' => 'cell_field37' ),
array( 'cell' => 'cell_field40' ),
array( 'cell' => 'cell_field45' ),
array( 'cell' => 'cell_field50' ),
array( 'cell' => 'cell_field55' ),
array( 'cell' => 'cell_field60' ),
array( 'cell' => 'cell_field65' ) ) ),
array( 'section' => 'body',
'cells' => array( array( 'cell' => 'cell_dpreview7',
'colspan' => 5 ),
array( 'cell' => 'cell_dpreview8',
'colspan' => 3 ),
array( 'cell' => 'cell_field13' ),
array( 'cell' => 'cell_field18' ),
array( 'cell' => 'cell_field23' ),
array( 'cell' => 'cell_field28' ),
array( 'cell' => 'cell_field33' ),
array( 'cell' => 'cell_field38' ),
array( 'cell' => 'cell_field41' ),
array( 'cell' => 'cell_field46' ),
array( 'cell' => 'cell_field51' ),
array( 'cell' => 'cell_field56' ),
array( 'cell' => 'cell_field61' ),
array( 'cell' => 'cell_field66' ) ) ),
array( 'section' => 'body',
'cells' => array( array( 'cell' => 'cell_dpreview6',
'colspan' => 5 ),
array( 'cell' => 'cell_dpreview9',
'colspan' => 3 ),
array( 'cell' => 'cell_field14' ),
array( 'cell' => 'cell_field19' ),
array( 'cell' => 'cell_field24' ),
array( 'cell' => 'cell_field29' ),
array( 'cell' => 'cell_field34' ),
array( 'cell' => 'cell_field39' ),
array( 'cell' => 'cell_field42' ),
array( 'cell' => 'cell_field47' ),
array( 'cell' => 'cell_field52' ),
array( 'cell' => 'cell_field57' ),
array( 'cell' => 'cell_field62' ),
array( 'cell' => 'cell_field67' ) ) ),
array( 'section' => 'body',
'cells' => array( array( 'cell' => 'cell_dpreview1',
'colspan' => 20 ) ) ),
array( 'section' => 'foot',
'cells' => array( array( 'cell' => 'footcell_field' ),
array( 'cell' => 'footcell_field1' ),
array( 'cell' => 'footcell_field2' ),
array( 'cell' => 'footcell_field3' ),
array( 'cell' => 'footcell_field4' ),
array( 'cell' => 'footcell_field5' ),
array( 'cell' => 'footcell_field6' ),
array( 'cell' => 'footcell_field7' ),
array( 'cell' => 'footcell_field14' ),
array( 'cell' => 'footcell_field16' ),
array( 'cell' => 'footcell_field18' ),
array( 'cell' => 'footcell_field20' ),
array( 'cell' => 'footcell_field22' ),
array( 'cell' => 'footcell_field24' ),
array( 'cell' => 'footcell_field9' ),
array( 'cell' => 'footcell_field11' ),
array( 'cell' => 'footcell_field26' ),
array( 'cell' => 'footcell_field28' ),
array( 'cell' => 'footcell_field30' ),
array( 'cell' => 'footcell_field32' ) ) ),
array( 'section' => 'foot',
'cells' => array( array( 'cell' => 'footcell_field8',
'colspan' => 4 ),
array( 'cell' => 'footcell_field12',
'colspan' => 4 ),
array( 'cell' => 'footcell_field15' ),
array( 'cell' => 'footcell_field17' ),
array( 'cell' => 'footcell_field19' ),
array( 'cell' => 'footcell_field21' ),
array( 'cell' => 'footcell_field23' ),
array( 'cell' => 'footcell_field25' ),
array( 'cell' => 'footcell_field10' ),
array( 'cell' => 'footcell_field13' ),
array( 'cell' => 'footcell_field27' ),
array( 'cell' => 'footcell_field29' ),
array( 'cell' => 'footcell_field31' ),
array( 'cell' => 'footcell_field33' ) ) ) ),
'cells' => array( 'headcell_field' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field7' ),
'field' => 'sol_rad',
'columnName' => 'field' ),
'cell_field' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field4' ),
'field' => 'sol_rad',
'columnName' => 'field' ),
'footcell_field' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field1' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field2' ),
'field' => 'sol_fecha',
'columnName' => 'field' ),
'cell_field1' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field1' ),
'field' => 'sol_fecha',
'columnName' => 'field' ),
'footcell_field1' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field2' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field11' ),
'field' => 'username_id',
'columnName' => 'field' ),
'cell_field2' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field10' ),
'field' => 'username_id',
'columnName' => 'field' ),
'footcell_field2' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field3' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field3' ),
'field' => 'sol_estado',
'columnName' => 'field' ),
'cell_field3' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field' ),
'field' => 'sol_estado',
'columnName' => 'field' ),
'footcell_field3' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field4' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field12' ),
'field' => 'sol_type',
'columnName' => 'field' ),
'cell_field4' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field5' ),
'field' => 'sol_type',
'columnName' => 'field' ),
'footcell_field4' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field5' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field13' ),
'field' => 'sol_userfr',
'columnName' => 'field' ),
'cell_field5' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field6' ),
'field' => 'sol_userfr',
'columnName' => 'field' ),
'footcell_field5' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field6' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field14' ),
'field' => 'sol_userto',
'columnName' => 'field' ),
'cell_field6' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field8' ),
'field' => 'sol_userto',
'columnName' => 'field' ),
'footcell_field6' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field7' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field15' ),
'field' => 'transact_id',
'columnName' => 'field' ),
'cell_field7' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field9' ),
'field' => 'transact_id',
'columnName' => 'field' ),
'footcell_field7' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'footcell_field8' => array( 'model' => 'footcell_field',
'items' => array(  ),
'height' => '200px',
'font-family' => 'Roboto' ),
'footcell_field12' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'cell_dpreview5' => array( 'model' => 'cell_dpreview',
'items' => array( 'grid_field_label5',
'details_preview' ),
'field' => 'sign_b_user',
'columnName' => 'field' ),
'cell_dpreview4' => array( 'model' => 'cell_dpreview',
'items' => array( 'grid_field_label2' ),
'field' => 'sign_a_user',
'columnName' => 'field' ),
'cell_dpreview3' => array( 'model' => 'cell_dpreview',
'items' => array(  ) ),
'cell_dpreview2' => array( 'model' => 'cell_dpreview',
'items' => array(  ) ),
'cell_dpreview1' => array( 'model' => 'cell_dpreview',
'items' => array(  ) ),
'footcell_field13' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'footcell_field11' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'cell_field9' => array( 'model' => 'cell_field',
'items' => array(  ) ),
'headcell_field9' => array( 'model' => 'headcell_field',
'items' => array( 'grid_field_label1' ),
'field' => 'sign_a_hash_v_date',
'columnName' => 'field' ),
'headcell_field8' => array( 'model' => 'headcell_field',
'items' => array( 'grid_field_label' ),
'field' => 'sign_a_hash_v',
'columnName' => 'field' ),
'footcell_field10' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'footcell_field9' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'cell_field8' => array( 'model' => 'cell_field',
'items' => array( 'grid_field' ),
'field' => 'sign_a_hash_v',
'columnName' => 'field' ),
'cell_dpreview6' => array( 'model' => 'cell_dpreview',
'items' => array( 'grid_field_label4',
'grid_field4' ),
'field' => 'sign_a_email',
'columnName' => 'field' ),
'cell_dpreview7' => array( 'model' => 'cell_dpreview',
'items' => array( 'grid_field_label3',
'grid_field3' ),
'field' => 'sign_a_documento',
'columnName' => 'field' ),
'cell_dpreview8' => array( 'model' => 'cell_dpreview',
'items' => array( 'grid_field_label6',
'grid_field6' ),
'field' => 'sign_b_documento',
'columnName' => 'field' ),
'cell_dpreview9' => array( 'model' => 'cell_dpreview',
'items' => array( 'grid_field_label7',
'grid_field7' ),
'field' => 'sign_b_email',
'columnName' => 'field' ),
'headcell_field10' => array( 'model' => 'headcell_field',
'items' => array(  ) ),
'cell_field10' => array( 'model' => 'cell_field',
'items' => array(  ) ),
'cell_field11' => array( 'model' => 'cell_field',
'items' => array(  ) ),
'cell_field12' => array( 'model' => 'cell_field',
'items' => array(  ) ),
'cell_field13' => array( 'model' => 'cell_field',
'items' => array(  ) ),
'cell_field14' => array( 'model' => 'cell_field',
'items' => array(  ) ),
'footcell_field14' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'footcell_field15' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field11' => array( 'model' => 'headcell_field',
'items' => array(  ) ),
'cell_field15' => array( 'model' => 'cell_field',
'items' => array(  ) ),
'cell_field16' => array( 'model' => 'cell_field',
'items' => array(  ) ),
'cell_field17' => array( 'model' => 'cell_field',
'items' => array(  ) ),
'cell_field18' => array( 'model' => 'cell_field',
'items' => array(  ) ),
'cell_field19' => array( 'model' => 'cell_field',
'items' => array(  ) ),
'footcell_field16' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'footcell_field17' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field12' => array( 'model' => 'headcell_field',
'items' => array(  ) ),
'cell_field20' => array( 'model' => 'cell_field',
'items' => array(  ) ),
'cell_field21' => array( 'model' => 'cell_field',
'items' => array(  ) ),
'cell_field22' => array( 'model' => 'cell_field',
'items' => array(  ) ),
'cell_field23' => array( 'model' => 'cell_field',
'items' => array(  ) ),
'cell_field24' => array( 'model' => 'cell_field',
'items' => array(  ) ),
'footcell_field18' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'footcell_field19' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field13' => array( 'model' => 'headcell_field',
'items' => array(  ) ),
'cell_field25' => array( 'model' => 'cell_field',
'items' => array(  ) ),
'cell_field26' => array( 'model' => 'cell_field',
'items' => array(  ) ),
'cell_field27' => array( 'model' => 'cell_field',
'items' => array(  ) ),
'cell_field28' => array( 'model' => 'cell_field',
'items' => array(  ) ),
'cell_field29' => array( 'model' => 'cell_field',
'items' => array(  ) ),
'footcell_field20' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'footcell_field21' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field14' => array( 'model' => 'headcell_field',
'items' => array(  ) ),
'cell_field30' => array( 'model' => 'cell_field',
'items' => array(  ) ),
'cell_field31' => array( 'model' => 'cell_field',
'items' => array(  ) ),
'cell_field32' => array( 'model' => 'cell_field',
'items' => array(  ) ),
'cell_field33' => array( 'model' => 'cell_field',
'items' => array(  ) ),
'cell_field34' => array( 'model' => 'cell_field',
'items' => array(  ) ),
'footcell_field22' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'footcell_field23' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field15' => array( 'model' => 'headcell_field',
'items' => array(  ) ),
'cell_field35' => array( 'model' => 'cell_field',
'items' => array(  ) ),
'cell_field36' => array( 'model' => 'cell_field',
'items' => array(  ) ),
'cell_field37' => array( 'model' => 'cell_field',
'items' => array(  ) ),
'cell_field38' => array( 'model' => 'cell_field',
'items' => array(  ) ),
'cell_field39' => array( 'model' => 'cell_field',
'items' => array(  ) ),
'footcell_field24' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'footcell_field25' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'cell_dpreview10' => array( 'model' => 'cell_dpreview',
'items' => array( 'grid_field5' ),
'field' => 'sign_b_user',
'columnName' => 'field' ),
'cell_dpreview11' => array( 'model' => 'cell_dpreview',
'items' => array( 'grid_field2' ),
'field' => 'sign_a_user',
'columnName' => 'field' ),
'cell_field40' => array( 'model' => 'cell_field',
'items' => array(  ) ),
'cell_field41' => array( 'model' => 'cell_field',
'items' => array(  ) ),
'cell_field42' => array( 'model' => 'cell_field',
'items' => array(  ) ),
'cell_field43' => array( 'model' => 'cell_field',
'items' => array( 'grid_field1' ),
'field' => 'sign_a_hash_v_date',
'columnName' => 'field' ),
'cell_field44' => array( 'model' => 'cell_field',
'items' => array(  ) ),
'cell_field45' => array( 'model' => 'cell_field',
'items' => array(  ) ),
'cell_field46' => array( 'model' => 'cell_field',
'items' => array(  ) ),
'cell_field47' => array( 'model' => 'cell_field',
'items' => array(  ) ),
'headcell_field16' => array( 'model' => 'headcell_field',
'items' => array( 'grid_field_label8' ),
'field' => 'sign_a_hash_v_ip',
'columnName' => 'field' ),
'cell_field48' => array( 'model' => 'cell_field',
'items' => array( 'grid_field8' ),
'field' => 'sign_a_hash_v_ip',
'columnName' => 'field' ),
'cell_field49' => array( 'model' => 'cell_field',
'items' => array(  ) ),
'cell_field50' => array( 'model' => 'cell_field',
'items' => array(  ) ),
'cell_field51' => array( 'model' => 'cell_field',
'items' => array(  ) ),
'cell_field52' => array( 'model' => 'cell_field',
'items' => array(  ) ),
'footcell_field26' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'footcell_field27' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field17' => array( 'model' => 'headcell_field',
'items' => array( 'grid_field_label9' ),
'field' => 'sign_b_hash_v',
'columnName' => 'field' ),
'cell_field53' => array( 'model' => 'cell_field',
'items' => array( 'grid_field9' ),
'field' => 'sign_b_hash_v',
'columnName' => 'field' ),
'cell_field54' => array( 'model' => 'cell_field',
'items' => array(  ) ),
'cell_field55' => array( 'model' => 'cell_field',
'items' => array(  ) ),
'cell_field56' => array( 'model' => 'cell_field',
'items' => array(  ) ),
'cell_field57' => array( 'model' => 'cell_field',
'items' => array(  ) ),
'footcell_field28' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'footcell_field29' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field18' => array( 'model' => 'headcell_field',
'items' => array( 'grid_field_label10' ),
'field' => 'sign_b_hash_v_date',
'columnName' => 'field' ),
'cell_field58' => array( 'model' => 'cell_field',
'items' => array( 'grid_field10' ),
'field' => 'sign_b_hash_v_date',
'columnName' => 'field' ),
'cell_field59' => array( 'model' => 'cell_field',
'items' => array(  ) ),
'cell_field60' => array( 'model' => 'cell_field',
'items' => array(  ) ),
'cell_field61' => array( 'model' => 'cell_field',
'items' => array(  ) ),
'cell_field62' => array( 'model' => 'cell_field',
'items' => array(  ) ),
'footcell_field30' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'footcell_field31' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field19' => array( 'model' => 'headcell_field',
'items' => array( 'grid_field_label11' ),
'field' => 'sign_b_hash_v_ip',
'columnName' => 'field' ),
'cell_field63' => array( 'model' => 'cell_field',
'items' => array( 'grid_field11' ),
'field' => 'sign_b_hash_v_ip',
'columnName' => 'field' ),
'cell_field64' => array( 'model' => 'cell_field',
'items' => array(  ) ),
'cell_field65' => array( 'model' => 'cell_field',
'items' => array(  ) ),
'cell_field66' => array( 'model' => 'cell_field',
'items' => array(  ) ),
'cell_field67' => array( 'model' => 'cell_field',
'items' => array(  ) ),
'footcell_field32' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'footcell_field33' => array( 'model' => 'footcell_field',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'print_header' => array( 'type' => 'print_header' ),
'print_subheader' => array( 'type' => 'print_subheader' ),
'print_pages' => array( 'type' => 'print_pages' ),
'simple_grid_field' => array( 'field' => 'sol_estado',
'type' => 'grid_field' ),
'simple_grid_field1' => array( 'field' => 'sol_fecha',
'type' => 'grid_field' ),
'simple_grid_field2' => array( 'type' => 'grid_field_label',
'field' => 'sol_fecha' ),
'simple_grid_field3' => array( 'type' => 'grid_field_label',
'field' => 'sol_estado' ),
'simple_grid_field4' => array( 'field' => 'sol_rad',
'type' => 'grid_field' ),
'simple_grid_field5' => array( 'field' => 'sol_type',
'type' => 'grid_field' ),
'simple_grid_field6' => array( 'field' => 'sol_userfr',
'type' => 'grid_field' ),
'simple_grid_field8' => array( 'field' => 'sol_userto',
'type' => 'grid_field' ),
'simple_grid_field9' => array( 'field' => 'transact_id',
'type' => 'grid_field' ),
'simple_grid_field10' => array( 'field' => 'username_id',
'type' => 'grid_field' ),
'details_preview' => array( 'type' => 'details_preview',
'table' => 'aldevindiv_sol_vinc_sign',
'items' => array(  ),
'popup' => false ),
'print_pdf' => array( 'type' => 'print_pdf',
'targetPages' => array(  ),
'splitModes' => array(  ),
'scopes' => array(  ) ),
'image' => array( 'type' => 'image',
'image' => array( 'image' => 'gob_mincit.png',
'source' => 2 ) ),
'simple_grid_field7' => array( 'type' => 'grid_field_label',
'field' => 'sol_rad' ),
'simple_grid_field11' => array( 'type' => 'grid_field_label',
'field' => 'username_id' ),
'simple_grid_field12' => array( 'type' => 'grid_field_label',
'field' => 'sol_type' ),
'simple_grid_field13' => array( 'type' => 'grid_field_label',
'field' => 'sol_userfr' ),
'simple_grid_field14' => array( 'type' => 'grid_field_label',
'field' => 'sol_userto' ),
'simple_grid_field15' => array( 'type' => 'grid_field_label',
'field' => 'transact_id' ),
'grid_field' => array( 'field' => 'sign_a_hash_v',
'type' => 'grid_field' ),
'grid_field_label' => array( 'type' => 'grid_field_label',
'field' => 'sign_a_hash_v' ),
'grid_field1' => array( 'field' => 'sign_a_hash_v_date',
'type' => 'grid_field' ),
'grid_field_label1' => array( 'type' => 'grid_field_label',
'field' => 'sign_a_hash_v_date' ),
'grid_field2' => array( 'field' => 'sign_a_user',
'type' => 'grid_field' ),
'grid_field_label2' => array( 'type' => 'grid_field_label',
'field' => 'sign_a_user' ),
'grid_field3' => array( 'field' => 'sign_a_documento',
'type' => 'grid_field' ),
'grid_field_label3' => array( 'type' => 'grid_field_label',
'field' => 'sign_a_documento' ),
'grid_field4' => array( 'field' => 'sign_a_email',
'type' => 'grid_field' ),
'grid_field_label4' => array( 'type' => 'grid_field_label',
'field' => 'sign_a_email' ),
'grid_field5' => array( 'field' => 'sign_b_user',
'type' => 'grid_field' ),
'grid_field_label5' => array( 'type' => 'grid_field_label',
'field' => 'sign_b_user' ),
'grid_field6' => array( 'field' => 'sign_b_documento',
'type' => 'grid_field' ),
'grid_field_label6' => array( 'type' => 'grid_field_label',
'field' => 'sign_b_documento' ),
'grid_field7' => array( 'field' => 'sign_b_email',
'type' => 'grid_field' ),
'grid_field_label7' => array( 'type' => 'grid_field_label',
'field' => 'sign_b_email' ),
'grid_field8' => array( 'field' => 'sign_a_hash_v_ip',
'type' => 'grid_field' ),
'grid_field_label8' => array( 'type' => 'grid_field_label',
'field' => 'sign_a_hash_v_ip' ),
'grid_field9' => array( 'field' => 'sign_b_hash_v',
'type' => 'grid_field' ),
'grid_field_label9' => array( 'type' => 'grid_field_label',
'field' => 'sign_b_hash_v' ),
'grid_field10' => array( 'field' => 'sign_b_hash_v_date',
'type' => 'grid_field' ),
'grid_field_label10' => array( 'type' => 'grid_field_label',
'field' => 'sign_b_hash_v_date' ),
'grid_field11' => array( 'field' => 'sign_b_hash_v_ip',
'type' => 'grid_field' ),
'grid_field_label11' => array( 'type' => 'grid_field_label',
'field' => 'sign_b_hash_v_ip' ) ),
'dbProps' => array(  ),
'version' => 14,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'listTotals' => 1 );
		?>