<?php
			$optionsArray = array( 'fields' => array( 'gridFields' => array( 'di_almacen',
'di_cuenta',
'di_codelem',
'cod_cta',
'di_nroplaca',
'di_nroserie',
'di_fechacompra',
'di_fecha_asigacion',
'di_funcionario',
'di_depsup',
'di_dep',
'di_valorcompra',
'almovdevdia_id_fk' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'di_cuenta' => array( 'import_field1' ),
'di_valorcompra' => array( 'import_field11' ),
'di_dep' => array( 'import_field10' ),
'di_depsup' => array( 'import_field9' ),
'di_funcionario' => array( 'import_field8' ),
'di_fecha_asigacion' => array( 'import_field7' ),
'di_fechacompra' => array( 'import_field6' ),
'di_nroserie' => array( 'import_field5' ),
'di_nroplaca' => array( 'import_field4' ),
'cod_cta' => array( 'import_field3' ),
'di_codelem' => array( 'import_field2' ),
'di_almacen' => array( 'import_field' ),
'almovdevdia_id_fk' => array( 'import_field12' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'import_header' ),
'grid' => array( 'import_field',
'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'import_header' => 'top',
'import_field' => 'grid',
'import_field1' => 'grid',
'import_field2' => 'grid',
'import_field3' => 'grid',
'import_field4' => 'grid',
'import_field5' => 'grid',
'import_field6' => 'grid',
'import_field7' => 'grid',
'import_field8' => 'grid',
'import_field9' => 'grid',
'import_field10' => 'grid',
'import_field11' => 'grid',
'import_field12' => 'grid' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'import_header' => array( 'import_header' ),
'import_field' => array( 'import_field1',
'import_field11',
'import_field10',
'import_field9',
'import_field8',
'import_field7',
'import_field6',
'import_field5',
'import_field4',
'import_field3',
'import_field2',
'import_field',
'import_field12' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false,
'menus' => array(  ),
'calcTotalsFor' => 1 ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'import',
'type' => 'import',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'import-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_header' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'import-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_field',
'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'import_header' => array( 'type' => 'import_header' ),
'import_field1' => array( 'field' => 'di_cuenta',
'type' => 'import_field' ),
'import_field11' => array( 'field' => 'di_valorcompra',
'type' => 'import_field' ),
'import_field10' => array( 'field' => 'di_dep',
'type' => 'import_field' ),
'import_field9' => array( 'field' => 'di_depsup',
'type' => 'import_field' ),
'import_field8' => array( 'field' => 'di_funcionario',
'type' => 'import_field' ),
'import_field7' => array( 'field' => 'di_fecha_asigacion',
'type' => 'import_field' ),
'import_field6' => array( 'field' => 'di_fechacompra',
'type' => 'import_field' ),
'import_field5' => array( 'field' => 'di_nroserie',
'type' => 'import_field' ),
'import_field4' => array( 'field' => 'di_nroplaca',
'type' => 'import_field' ),
'import_field3' => array( 'field' => 'cod_cta',
'type' => 'import_field' ),
'import_field2' => array( 'field' => 'di_codelem',
'type' => 'import_field' ),
'import_field' => array( 'field' => 'di_almacen',
'type' => 'import_field' ),
'import_field12' => array( 'field' => 'almovdevdia_id_fk',
'type' => 'import_field' ) ),
'dbProps' => array(  ),
'version' => 14,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'listTotals' => 1 );
		?>