<?php
			$optionsArray = array( 'totals' => array( 'almovconsdia_id' => array( 'totalsType' => '' ),
'doclasedoc_id_fk' => array( 'totalsType' => '' ),
'consumo_id_fk' => array( 'totalsType' => '' ),
'mcdclasedoc' => array( 'totalsType' => '' ),
'mcdnrodoc' => array( 'totalsType' => '' ),
'mcdfechadoc' => array( 'totalsType' => '' ),
'mcdtipoestruc' => array( 'totalsType' => '' ),
'mcdalmacen' => array( 'totalsType' => '' ),
'mcdcuenta' => array( 'totalsType' => '' ),
'mcdcodelem' => array( 'totalsType' => '' ),
'mcdnomelem' => array( 'totalsType' => '' ),
'mcd_cantmovto' => array( 'totalsType' => '' ),
'mcd_saldant' => array( 'totalsType' => '' ),
'mcd_valunitant' => array( 'totalsType' => '' ),
'mcd_valmovto' => array( 'totalsType' => '' ),
'mcd_tax' => array( 'totalsType' => '' ),
'geusuario' => array( 'totalsType' => '' ),
'mcd_cantasignada' => array( 'totalsType' => '' ),
'gefechaactua' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array( 'almovconsdia_id',
'doclasedoc_id_fk',
'geusuario',
'mcd_cantmovto',
'mcd_valmovto',
'mcd_valunitant',
'mcdalmacen',
'mcdclasedoc',
'mcdcodelem',
'mcdcuenta',
'mcdfechadoc',
'mcdnrodoc',
'consumo_id_fk',
'mcdnomelem' ),
'exportFields' => array( 'almovconsdia_id',
'doclasedoc_id_fk',
'geusuario',
'mcd_cantmovto',
'mcd_valmovto',
'mcd_valunitant',
'mcdalmacen',
'mcdclasedoc',
'mcdcodelem',
'mcdcuenta',
'mcdfechadoc',
'mcdnrodoc',
'consumo_id_fk',
'mcdnomelem' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'almovconsdia_id' => array( 'export_field' ),
'doclasedoc_id_fk' => array( 'export_field1' ),
'geusuario' => array( 'export_field3' ),
'mcd_cantmovto' => array( 'export_field5' ),
'mcd_valmovto' => array( 'export_field8' ),
'mcd_valunitant' => array( 'export_field9' ),
'mcdalmacen' => array( 'export_field10' ),
'mcdclasedoc' => array( 'export_field11' ),
'mcdcodelem' => array( 'export_field12' ),
'mcdcuenta' => array( 'export_field13' ),
'mcdfechadoc' => array( 'export_field14' ),
'mcdnrodoc' => array( 'export_field15' ),
'consumo_id_fk' => array( 'export_field17' ),
'mcdnomelem' => array( 'export_field18' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'export_header' ),
'grid' => array( 'export_field',
'export_field1',
'export_field3',
'export_field5',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14',
'export_field15',
'export_field17',
'export_field18' ),
'footer' => array( 'export_export',
'export_cancel' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'export_header' => 'top',
'export_field' => 'grid',
'export_field1' => 'grid',
'export_field3' => 'grid',
'export_field5' => 'grid',
'export_field8' => 'grid',
'export_field9' => 'grid',
'export_field10' => 'grid',
'export_field11' => 'grid',
'export_field12' => 'grid',
'export_field13' => 'grid',
'export_field14' => 'grid',
'export_field15' => 'grid',
'export_field17' => 'grid',
'export_field18' => 'grid',
'export_export' => 'footer',
'export_cancel' => 'footer' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'export_header' => array( 'export_header' ),
'export_export' => array( 'export_export' ),
'export_cancel' => array( 'export_cancel' ),
'export_field' => array( 'export_field',
'export_field1',
'export_field3',
'export_field5',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14',
'export_field15',
'export_field17',
'export_field18' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false,
'menus' => array(  ),
'calcTotalsFor' => 1 ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'export' => array( 'format' => 2,
'selectFields' => false,
'delimiter' => ',',
'selectDelimiter' => false,
'exportFileTypes' => array( 'excel' => true,
'word' => true,
'csv' => true,
'xml' => false ) ) );
			$pageArray = array( 'id' => 'export',
'type' => 'export',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'export-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_header' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'export-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_field',
'export_field1',
'export_field3',
'export_field5',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14',
'export_field15',
'export_field17',
'export_field18' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'footer' => array( 'modelId' => 'export-footer',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ),
'c2' => array( 'model' => 'c2',
'items' => array( 'export_export',
'export_cancel' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'export_header' => array( 'type' => 'export_header' ),
'export_export' => array( 'type' => 'export_export' ),
'export_cancel' => array( 'type' => 'export_cancel' ),
'export_field' => array( 'field' => 'almovconsdia_id',
'type' => 'export_field' ),
'export_field1' => array( 'field' => 'doclasedoc_id_fk',
'type' => 'export_field' ),
'export_field3' => array( 'field' => 'geusuario',
'type' => 'export_field' ),
'export_field5' => array( 'field' => 'mcd_cantmovto',
'type' => 'export_field' ),
'export_field8' => array( 'field' => 'mcd_valmovto',
'type' => 'export_field' ),
'export_field9' => array( 'field' => 'mcd_valunitant',
'type' => 'export_field' ),
'export_field10' => array( 'field' => 'mcdalmacen',
'type' => 'export_field' ),
'export_field11' => array( 'field' => 'mcdclasedoc',
'type' => 'export_field' ),
'export_field12' => array( 'field' => 'mcdcodelem',
'type' => 'export_field' ),
'export_field13' => array( 'field' => 'mcdcuenta',
'type' => 'export_field' ),
'export_field14' => array( 'field' => 'mcdfechadoc',
'type' => 'export_field' ),
'export_field15' => array( 'field' => 'mcdnrodoc',
'type' => 'export_field' ),
'export_field17' => array( 'field' => 'consumo_id_fk',
'type' => 'export_field' ),
'export_field18' => array( 'field' => 'mcdnomelem',
'type' => 'export_field' ) ),
'dbProps' => array(  ),
'version' => 14,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'listTotals' => 1,
'exportFormat' => 2,
'exportDelimiter' => ',',
'exportSelectDelimiter' => false,
'exportSelectFields' => false );
		?>