<?php
			$optionsArray = array( 'totals' => array( 'almovinddia_id' => array( 'totalsType' => '' ),
'md_legalizado' => array( 'totalsType' => '' ),
'sys_status' => array( 'totalsType' => '' ),
'doclasedoc_id_fk' => array( 'totalsType' => '' ),
'almovdevdia_id_fk' => array( 'totalsType' => '' ),
'aldevindiv_id_fk' => array( 'totalsType' => '' ),
'midclasedoc' => array( 'totalsType' => '' ),
'midnrodoc' => array( 'totalsType' => '' ),
'midfechadoc' => array( 'totalsType' => '' ),
'midalmacen' => array( 'totalsType' => '' ),
'devolutivo_id_FK' => array( 'totalsType' => '' ),
'midcuenta' => array( 'totalsType' => '' ),
'midcodelem' => array( 'totalsType' => '' ),
'midnroplaca' => array( 'totalsType' => '' ),
'midnroserie' => array( 'totalsType' => '' ),
'midfuncionario' => array( 'totalsType' => '' ),
'mid_valunit' => array( 'totalsType' => '' ),
'mid_tax' => array( 'totalsType' => '' ),
'mid_valormovto' => array( 'totalsType' => '' ),
'mid_vidautiladi' => array( 'totalsType' => '' ),
'mid_estadocons' => array( 'totalsType' => '' ),
'mid_estadoelem' => array( 'totalsType' => '' ),
'mid_coddetalleestado' => array( 'totalsType' => '' ),
'geusuario' => array( 'totalsType' => '' ),
'gefechaactua' => array( 'totalsType' => '' ),
'sys_status_fecha' => array( 'totalsType' => '' ),
'sys_status_user' => array( 'totalsType' => '' ),
'sys_document_func' => array( 'totalsType' => '' ),
'sys_doclasedoc_id_fk' => array( 'totalsType' => '' ),
'mid_valor_dep_acum' => array( 'totalsType' => '' ),
'nicsp_fecha_inicio_dep' => array( 'totalsType' => '' ),
'nicsp_costodesmant' => array( 'totalsType' => '' ),
'nicsp_valorresidual' => array( 'totalsType' => '' ),
'nicsp_valordeterioro' => array( 'totalsType' => '' ),
'nicsp_basedepreciable' => array( 'totalsType' => '' ),
'nicsp_costo' => array( 'totalsType' => '' ),
'nicsp_codigo_ppe' => array( 'totalsType' => '' ),
'nicsp_vigenciapm' => array( 'totalsType' => '' ),
'nicsp_politicamaterialidad' => array( 'totalsType' => '' ),
'nicsp_vidautil' => array( 'totalsType' => '' ),
'nicsp_fechacorte' => array( 'totalsType' => '' ),
'nicsp_dias' => array( 'totalsType' => '' ),
'nicsp_meses' => array( 'totalsType' => '' ),
'nicsp_depreciamensual' => array( 'totalsType' => '' ),
'nicsp_depreciaacumulada' => array( 'totalsType' => '' ),
'nicsp_fechacorte_hist' => array( 'totalsType' => '' ),
'nicsp_depreciaacumulada_hist' => array( 'totalsType' => '' ),
'nicsp_vnl' => array( 'totalsType' => '' ),
'nicsp_vida_remanente' => array( 'totalsType' => '' ),
'cod_cta' => array( 'totalsType' => '' ),
'syslastupd' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array( 'midcuenta',
'midcodelem',
'midnroplaca',
'midnroserie',
'mid_valunit',
'devolutivo_id_FK',
'md_legalizado' ),
'exportFields' => array( 'midcuenta',
'midcodelem',
'midnroplaca',
'midnroserie',
'mid_valunit',
'devolutivo_id_FK',
'md_legalizado' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'midcuenta' => array( 'export_field9' ),
'midcodelem' => array( 'export_field10' ),
'midnroplaca' => array( 'export_field11' ),
'midnroserie' => array( 'export_field12' ),
'mid_valunit' => array( 'export_field14' ),
'devolutivo_id_FK' => array( 'export_field' ),
'md_legalizado' => array( 'export_field1' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'export_header' ),
'grid' => array( 'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field14',
'export_field',
'export_field1' ),
'footer' => array( 'export_export',
'export_cancel' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'export_header' => 'top',
'export_field9' => 'grid',
'export_field10' => 'grid',
'export_field11' => 'grid',
'export_field12' => 'grid',
'export_field14' => 'grid',
'export_field' => 'grid',
'export_field1' => 'grid',
'export_export' => 'footer',
'export_cancel' => 'footer' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'export_header' => array( 'export_header' ),
'export_export' => array( 'export_export' ),
'export_cancel' => array( 'export_cancel' ),
'export_field' => array( 'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field14',
'export_field',
'export_field1' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false,
'menus' => array(  ),
'calcTotalsFor' => 1 ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'export' => array( 'format' => 2,
'selectFields' => false,
'delimiter' => ',',
'selectDelimiter' => false,
'exportFileTypes' => array( 'excel' => true,
'word' => true,
'csv' => true,
'xml' => false ) ) );
			$pageArray = array( 'id' => 'export',
'type' => 'export',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'export-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_header' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'export-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field14',
'export_field',
'export_field1' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'footer' => array( 'modelId' => 'export-footer',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ),
'c2' => array( 'model' => 'c2',
'items' => array( 'export_export',
'export_cancel' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'export_header' => array( 'type' => 'export_header' ),
'export_export' => array( 'type' => 'export_export' ),
'export_cancel' => array( 'type' => 'export_cancel' ),
'export_field9' => array( 'field' => 'midcuenta',
'type' => 'export_field' ),
'export_field10' => array( 'field' => 'midcodelem',
'type' => 'export_field' ),
'export_field11' => array( 'field' => 'midnroplaca',
'type' => 'export_field' ),
'export_field12' => array( 'field' => 'midnroserie',
'type' => 'export_field' ),
'export_field14' => array( 'field' => 'mid_valunit',
'type' => 'export_field' ),
'export_field' => array( 'field' => 'devolutivo_id_FK',
'type' => 'export_field' ),
'export_field1' => array( 'field' => 'md_legalizado',
'type' => 'export_field' ) ),
'dbProps' => array(  ),
'version' => 14,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'listTotals' => 1,
'exportFormat' => 2,
'exportDelimiter' => ',',
'exportSelectDelimiter' => false,
'exportSelectFields' => false );
		?>