<?php
			$optionsArray = array( 'details' => array( 'almovinddia_ingresos_d' => array( 'displayPreview' => 2,
'previewPageId' => '' ) ),
'master' => array( 'gedocumentos_ingresos' => array( 'preview' => false ) ),
'captcha' => array( 'captcha' => false ),
'fields' => array( 'gridFields' => array( 'doclasedoc_id_fk',
'geusuario',
'mdd_cantmovto',
'mdd_valunit',
'mddalmacen',
'mddclasedoc',
'mddcodelem',
'mddcuenta',
'mddfechadoc',
'mddnrodoc',
'mddnomelem',
'devolutivo_id_FK',
'mdd_cantmovto_verifica' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'doclasedoc_id_fk' => array( 'integrated_edit_field',
'edit_field_label1',
'edit_field_tooltip1' ),
'geusuario' => array( 'integrated_edit_field2' ),
'mdd_cantmovto' => array( 'integrated_edit_field3',
'edit_field_label',
'edit_field_tooltip' ),
'mdd_valunit' => array( 'integrated_edit_field6' ),
'mddalmacen' => array( 'integrated_edit_field7' ),
'mddclasedoc' => array( 'integrated_edit_field8' ),
'mddcodelem' => array( 'integrated_edit_field9' ),
'mddcuenta' => array( 'integrated_edit_field10' ),
'mddfechadoc' => array( 'integrated_edit_field11' ),
'mddnrodoc' => array( 'integrated_edit_field12',
'edit_field_label2',
'edit_field_tooltip2' ),
'mddnomelem' => array( 'integrated_edit_field14' ),
'devolutivo_id_FK' => array( 'integrated_edit_field1' ),
'mdd_cantmovto_verifica' => array( 'integrated_edit_field4' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'above-grid' => array( 'add_message' ),
'below-grid' => array( 'add_save',
'add_reset',
'add_back_list',
'add_cancel' ),
'supertop' => array( 'expand_menu_button',
'collapse_button',
'loginform_login',
'username_button' ),
'left' => array( 'logo',
'expand_button',
'menu' ),
'top' => array( 'add_header' ),
'grid' => array( 'tabs',
'edit_field_label1',
'integrated_edit_field',
'edit_field_tooltip1',
'integrated_edit_field7',
'edit_field_label2',
'integrated_edit_field12',
'edit_field_tooltip2',
'integrated_edit_field11',
'integrated_edit_field8' ),
'section' => array( 'integrated_edit_field14',
'integrated_edit_field6',
'integrated_edit_field1',
'integrated_edit_field10',
'integrated_edit_field9',
'edit_field_label',
'integrated_edit_field3',
'edit_field_tooltip' ),
'section1' => array( 'integrated_edit_field2',
'integrated_edit_field4' ) ),
'formXtTags' => array( 'above-grid' => array( 'message_block' ) ),
'itemForms' => array( 'add_message' => 'above-grid',
'add_save' => 'below-grid',
'add_reset' => 'below-grid',
'add_back_list' => 'below-grid',
'add_cancel' => 'below-grid',
'expand_menu_button' => 'supertop',
'collapse_button' => 'supertop',
'loginform_login' => 'supertop',
'username_button' => 'supertop',
'logo' => 'left',
'expand_button' => 'left',
'menu' => 'left',
'add_header' => 'top',
'tabs' => 'grid',
'edit_field_label1' => 'grid',
'integrated_edit_field' => 'grid',
'edit_field_tooltip1' => 'grid',
'integrated_edit_field7' => 'grid',
'edit_field_label2' => 'grid',
'integrated_edit_field12' => 'grid',
'edit_field_tooltip2' => 'grid',
'integrated_edit_field11' => 'grid',
'integrated_edit_field8' => 'grid',
'integrated_edit_field14' => 'section',
'integrated_edit_field6' => 'section',
'integrated_edit_field1' => 'section',
'integrated_edit_field10' => 'section',
'integrated_edit_field9' => 'section',
'edit_field_label' => 'section',
'integrated_edit_field3' => 'section',
'edit_field_tooltip' => 'section',
'integrated_edit_field2' => 'section1',
'integrated_edit_field4' => 'section1' ),
'itemLocations' => array( 'tabs' => array( 'location' => 'grid',
'cellId' => 'c' ),
'edit_field_label1' => array( 'location' => 'grid',
'cellId' => 'c5' ),
'integrated_edit_field' => array( 'location' => 'grid',
'cellId' => 'c5' ),
'edit_field_tooltip1' => array( 'location' => 'grid',
'cellId' => 'c5' ),
'integrated_edit_field7' => array( 'location' => 'grid',
'cellId' => 'c6' ),
'edit_field_label2' => array( 'location' => 'grid',
'cellId' => 'c7' ),
'integrated_edit_field12' => array( 'location' => 'grid',
'cellId' => 'c7' ),
'edit_field_tooltip2' => array( 'location' => 'grid',
'cellId' => 'c7' ),
'integrated_edit_field11' => array( 'location' => 'grid',
'cellId' => 'c8' ),
'integrated_edit_field8' => array( 'location' => 'grid',
'cellId' => 'c10' ),
'integrated_edit_field14' => array( 'location' => 'section',
'cellId' => 'c1' ),
'integrated_edit_field6' => array( 'location' => 'section',
'cellId' => 'c' ),
'integrated_edit_field1' => array( 'location' => 'section',
'cellId' => 'c10' ),
'integrated_edit_field10' => array( 'location' => 'section',
'cellId' => 'c11' ),
'integrated_edit_field9' => array( 'location' => 'section',
'cellId' => 'c12' ),
'edit_field_label' => array( 'location' => 'section',
'cellId' => 'c14' ),
'integrated_edit_field3' => array( 'location' => 'section',
'cellId' => 'c14' ),
'edit_field_tooltip' => array( 'location' => 'section',
'cellId' => 'c14' ),
'integrated_edit_field2' => array( 'location' => 'section1',
'cellId' => 'c1' ),
'integrated_edit_field4' => array( 'location' => 'section1',
'cellId' => 'c1' ) ),
'itemVisiblity' => array( 'expand_menu_button' => 2,
'expand_button' => 5 ) ),
'itemsByType' => array( 'add_header' => array( 'add_header' ),
'add_back_list' => array( 'add_back_list' ),
'add_cancel' => array( 'add_cancel' ),
'add_message' => array( 'add_message' ),
'add_save' => array( 'add_save' ),
'add_reset' => array( 'add_reset' ),
'logo' => array( 'logo' ),
'menu' => array( 'menu' ),
'username_button' => array( 'username_button' ),
'loginform_login' => array( 'loginform_login' ),
'userinfo_link' => array( 'userinfo_link' ),
'logout_link' => array( 'logout_link' ),
'changepassword_link' => array( 'changepassword_link' ),
'expand_menu_button' => array( 'expand_menu_button' ),
'collapse_button' => array( 'collapse_button' ),
'edit_field' => array( 'integrated_edit_field',
'integrated_edit_field3',
'integrated_edit_field12' ),
'integrated_edit_field' => array( 'integrated_edit_field2',
'integrated_edit_field6',
'integrated_edit_field7',
'integrated_edit_field8',
'integrated_edit_field9',
'integrated_edit_field10',
'integrated_edit_field11',
'integrated_edit_field14',
'integrated_edit_field1',
'integrated_edit_field4' ),
'tabs' => array( 'tabs' ),
'edit_field_label' => array( 'edit_field_label',
'edit_field_label1',
'edit_field_label2' ),
'edit_field_tooltip' => array( 'edit_field_tooltip',
'edit_field_tooltip1',
'edit_field_tooltip2' ),
'expand_button' => array( 'expand_button' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'c5' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'edit_field_label1',
'integrated_edit_field',
'edit_field_tooltip1' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c6' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field7' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c7' => array( 'cols' => array( 2 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'edit_field_label2',
'integrated_edit_field12',
'edit_field_tooltip2' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c8' => array( 'cols' => array( 3 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field11' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c10' => array( 'cols' => array( 0,
1 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field8' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c12' => array( 'cols' => array( 2 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c13' => array( 'cols' => array( 3 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 0,
1,
2,
3 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'tabs' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c3' => array( 'cols' => array( 0,
1,
2,
3 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ) ),
'width' => 4,
'height' => 4 ),
'section' => array( 'cells' => array( 'c10' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field1' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c11' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field10' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c12' => array( 'cols' => array( 2 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field9' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c1' => array( 'cols' => array( 0,
1,
2 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field14' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 0,
1 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field6' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c14' => array( 'cols' => array( 2 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'edit_field_label',
'integrated_edit_field3',
'edit_field_tooltip' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 3,
'height' => 3 ),
'section1' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field2',
'integrated_edit_field4' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 1 ) ) ),
'loginForm' => array( 'loginForm' => 0 ),
'page' => array( 'verticalBar' => true,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false,
'menus' => array( array( 'id' => 'main',
'horizontal' => false ) ),
'calcTotalsFor' => 1 ),
'misc' => array( 'type' => 'add',
'breadcrumb' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'add',
'type' => 'add',
'layoutId' => 'leftbar',
'disabled' => 0,
'default' => 0,
'forms' => array( 'above-grid' => array( 'modelId' => 'add-above-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'add_message' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'add-below-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'add_save',
'add_reset',
'add_back_list',
'add_cancel' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'supertop' => array( 'modelId' => 'leftbar-top-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'expand_menu_button',
'collapse_button' ) ),
'c2' => array( 'model' => 'c2',
'items' => array( 'loginform_login',
'username_button' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'left' => array( 'modelId' => 'leftbar-menu',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c0' ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c0' => array( 'model' => 'c0',
'items' => array( 'logo',
'expand_button' ) ),
'c1' => array( 'model' => 'c1',
'items' => array( 'menu' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'add-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'add_header' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'section' => '',
'cells' => array( array( 'cell' => 'c5' ),
array( 'cell' => 'c6' ),
array( 'cell' => 'c7' ),
array( 'cell' => 'c8' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c10',
'colspan' => 2 ),
array( 'cell' => 'c12' ),
array( 'cell' => 'c13' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c',
'colspan' => 4 ) ) ),
array( 'cells' => array( array( 'cell' => 'c3',
'colspan' => 4 ) ),
'section' => '' ) ),
'cells' => array( 'c3' => array( 'model' => 'c3',
'items' => array(  ) ),
'c' => array( 'model' => 'c3',
'items' => array( 'tabs' ) ),
'c5' => array( 'model' => 'c3',
'items' => array( 'edit_field_label1',
'integrated_edit_field',
'edit_field_tooltip1' ) ),
'c6' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field7' ) ),
'c7' => array( 'model' => 'c3',
'items' => array( 'edit_field_label2',
'integrated_edit_field12',
'edit_field_tooltip2' ) ),
'c8' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field11' ) ),
'c10' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field8' ) ),
'c12' => array( 'model' => 'c3',
'items' => array(  ) ),
'c13' => array( 'model' => 'c3',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'section' => '',
'cells' => array( array( 'cell' => 'c10' ),
array( 'cell' => 'c11' ),
array( 'cell' => 'c12' ) ) ),
array( 'cells' => array( array( 'cell' => 'c1',
'colspan' => 3 ) ),
'section' => '' ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c',
'colspan' => 2 ),
array( 'cell' => 'c14' ) ) ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field14' ),
'useFullWidth' => true ),
'c' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field6' ) ),
'c10' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field1' ) ),
'c11' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field10' ) ),
'c12' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field9' ) ),
'c14' => array( 'model' => 'c3',
'items' => array( 'edit_field_label',
'integrated_edit_field3',
'edit_field_tooltip' ) ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section1' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field2',
'integrated_edit_field4' ) ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ) ),
'items' => array( 'add_header' => array( 'type' => 'add_header',
'title' => array( 'page' => 'add',
'table' => 'almovdevdia_ingresos_d',
'type' => 7 ),
'font-family' => 'Roboto',
'bold' => true,
'font-size' => '25px',
'color' => '#116bf0' ),
'add_back_list' => array( 'type' => 'add_back_list' ),
'add_cancel' => array( 'type' => 'add_cancel' ),
'add_message' => array( 'type' => 'add_message' ),
'add_save' => array( 'type' => 'add_save' ),
'add_reset' => array( 'type' => 'add_reset' ),
'logo' => array( 'type' => 'logo' ),
'menu' => array( 'type' => 'menu' ),
'username_button' => array( 'type' => 'username_button',
'items' => array( 'userinfo_link',
'logout_link',
'changepassword_link' ) ),
'loginform_login' => array( 'type' => 'loginform_login',
'popup' => false ),
'userinfo_link' => array( 'type' => 'userinfo_link' ),
'logout_link' => array( 'type' => 'logout_link' ),
'changepassword_link' => array( 'type' => 'changepassword_link' ),
'expand_menu_button' => array( 'type' => 'expand_menu_button' ),
'collapse_button' => array( 'type' => 'collapse_button' ),
'integrated_edit_field' => array( 'field' => 'doclasedoc_id_fk',
'type' => 'edit_field',
'orientation' => 0,
'label' => array( 'field' => 'doclasedoc_id_fk',
'table' => 'almovdevdia_ingresos_d',
'type' => 3 ),
'joined' => false,
'separated' => true,
'font-family' => 'Roboto',
'bold' => true ),
'integrated_edit_field2' => array( 'field' => 'geusuario',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field3' => array( 'field' => 'mdd_cantmovto',
'type' => 'edit_field',
'orientation' => 0,
'joined' => false,
'separated' => true ),
'integrated_edit_field6' => array( 'field' => 'mdd_valunit',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field7' => array( 'field' => 'mddalmacen',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field8' => array( 'field' => 'mddclasedoc',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field9' => array( 'field' => 'mddcodelem',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field10' => array( 'field' => 'mddcuenta',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field11' => array( 'field' => 'mddfechadoc',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field12' => array( 'field' => 'mddnrodoc',
'type' => 'edit_field',
'orientation' => 0,
'joined' => false,
'separated' => true,
'font-family' => 'Roboto',
'bold' => true ),
'tabs' => array( 'type' => 'tabs',
'titles' => array( array( 'text' => 'Información de elementos',
'type' => 0 ),
array( 'text' => '',
'type' => 0 ) ),
'locations' => array( 'section',
'section1' ),
'bsStyle' => 'default',
'panelType' => 2 ),
'integrated_edit_field14' => array( 'field' => 'mddnomelem',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field1' => array( 'field' => 'devolutivo_id_FK',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 'devolutivo_id_FK',
'table' => 'almovdevdia_ingresos_d',
'type' => 3 ),
'tooltip' => array( 'field' => 'devolutivo_id_FK',
'table' => null,
'type' => 4 ) ),
'integrated_edit_field4' => array( 'field' => 'mdd_cantmovto_verifica',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'edit_field_label' => array( 'type' => 'edit_field_label',
'field' => 'mdd_cantmovto',
'separated' => true ),
'edit_field_tooltip' => array( 'type' => 'edit_field_tooltip',
'field' => 'mdd_cantmovto',
'separated' => true,
'tooltip' => array( 'field' => 'mdd_cantmovto',
'table' => null,
'type' => 4 ) ),
'edit_field_label1' => array( 'type' => 'edit_field_label',
'field' => 'doclasedoc_id_fk',
'separated' => true ),
'edit_field_tooltip1' => array( 'type' => 'edit_field_tooltip',
'field' => 'doclasedoc_id_fk',
'separated' => true ),
'edit_field_label2' => array( 'type' => 'edit_field_label',
'field' => 'mddnrodoc',
'separated' => true ),
'edit_field_tooltip2' => array( 'type' => 'edit_field_tooltip',
'field' => 'mddnrodoc',
'separated' => true ),
'expand_button' => array( 'type' => 'expand_button' ) ),
'dbProps' => array(  ),
'version' => 14,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'listTotals' => 1 );
		?>