<?php
$dalTablealmovinddia = array();
$dalTablealmovinddia["almovinddia_id"] = array("type"=>3,"varname"=>"almovinddia_id", "name" => "almovinddia_id", "autoInc" => "1");
$dalTablealmovinddia["md_legalizado"] = array("type"=>16,"varname"=>"md_legalizado", "name" => "md_legalizado", "autoInc" => "0");
$dalTablealmovinddia["sys_status"] = array("type"=>16,"varname"=>"sys_status", "name" => "sys_status", "autoInc" => "0");
$dalTablealmovinddia["doclasedoc_id_fk"] = array("type"=>3,"varname"=>"doclasedoc_id_fk", "name" => "doclasedoc_id_fk", "autoInc" => "0");
$dalTablealmovinddia["almovdevdia_id_fk"] = array("type"=>3,"varname"=>"almovdevdia_id_fk", "name" => "almovdevdia_id_fk", "autoInc" => "0");
$dalTablealmovinddia["aldevindiv_id_fk"] = array("type"=>3,"varname"=>"aldevindiv_id_fk", "name" => "aldevindiv_id_fk", "autoInc" => "0");
$dalTablealmovinddia["midclasedoc"] = array("type"=>3,"varname"=>"midclasedoc", "name" => "midclasedoc", "autoInc" => "0");
$dalTablealmovinddia["midnrodoc"] = array("type"=>3,"varname"=>"midnrodoc", "name" => "midnrodoc", "autoInc" => "0");
$dalTablealmovinddia["midfechadoc"] = array("type"=>7,"varname"=>"midfechadoc", "name" => "midfechadoc", "autoInc" => "0");
$dalTablealmovinddia["midalmacen"] = array("type"=>3,"varname"=>"midalmacen", "name" => "midalmacen", "autoInc" => "0");
$dalTablealmovinddia["devolutivo_id_FK"] = array("type"=>3,"varname"=>"devolutivo_id_FK", "name" => "devolutivo_id_FK", "autoInc" => "0");
$dalTablealmovinddia["midcuenta"] = array("type"=>200,"varname"=>"midcuenta", "name" => "midcuenta", "autoInc" => "0");
$dalTablealmovinddia["midcodelem"] = array("type"=>3,"varname"=>"midcodelem", "name" => "midcodelem", "autoInc" => "0");
$dalTablealmovinddia["midnroplaca"] = array("type"=>200,"varname"=>"midnroplaca", "name" => "midnroplaca", "autoInc" => "0");
$dalTablealmovinddia["midnroserie"] = array("type"=>200,"varname"=>"midnroserie", "name" => "midnroserie", "autoInc" => "0");
$dalTablealmovinddia["midfuncionario"] = array("type"=>200,"varname"=>"midfuncionario", "name" => "midfuncionario", "autoInc" => "0");
$dalTablealmovinddia["mid_valunit"] = array("type"=>5,"varname"=>"mid_valunit", "name" => "mid_valunit", "autoInc" => "0");
$dalTablealmovinddia["mid_tax"] = array("type"=>5,"varname"=>"mid_tax", "name" => "mid_tax", "autoInc" => "0");
$dalTablealmovinddia["mid_valormovto"] = array("type"=>5,"varname"=>"mid_valormovto", "name" => "mid_valormovto", "autoInc" => "0");
$dalTablealmovinddia["mid_vidautiladi"] = array("type"=>3,"varname"=>"mid_vidautiladi", "name" => "mid_vidautiladi", "autoInc" => "0");
$dalTablealmovinddia["mid_estadocons"] = array("type"=>200,"varname"=>"mid_estadocons", "name" => "mid_estadocons", "autoInc" => "0");
$dalTablealmovinddia["mid_estadoelem"] = array("type"=>200,"varname"=>"mid_estadoelem", "name" => "mid_estadoelem", "autoInc" => "0");
$dalTablealmovinddia["mid_coddetalleestado"] = array("type"=>3,"varname"=>"mid_coddetalleestado", "name" => "mid_coddetalleestado", "autoInc" => "0");
$dalTablealmovinddia["geusuario"] = array("type"=>200,"varname"=>"geusuario", "name" => "geusuario", "autoInc" => "0");
$dalTablealmovinddia["gefechaactua"] = array("type"=>135,"varname"=>"gefechaactua", "name" => "gefechaactua", "autoInc" => "0");
$dalTablealmovinddia["sys_status_fecha"] = array("type"=>135,"varname"=>"sys_status_fecha", "name" => "sys_status_fecha", "autoInc" => "0");
$dalTablealmovinddia["sys_status_user"] = array("type"=>200,"varname"=>"sys_status_user", "name" => "sys_status_user", "autoInc" => "0");
$dalTablealmovinddia["sys_document_func"] = array("type"=>200,"varname"=>"sys_document_func", "name" => "sys_document_func", "autoInc" => "0");
$dalTablealmovinddia["sys_doclasedoc_id_fk"] = array("type"=>3,"varname"=>"sys_doclasedoc_id_fk", "name" => "sys_doclasedoc_id_fk", "autoInc" => "0");
$dalTablealmovinddia["mid_valor_dep_acum"] = array("type"=>5,"varname"=>"mid_valor_dep_acum", "name" => "mid_valor_dep_acum", "autoInc" => "0");
$dalTablealmovinddia["nicsp_fecha_inicio_dep"] = array("type"=>7,"varname"=>"nicsp_fecha_inicio_dep", "name" => "nicsp_fecha_inicio_dep", "autoInc" => "0");
$dalTablealmovinddia["nicsp_costodesmant"] = array("type"=>5,"varname"=>"nicsp_costodesmant", "name" => "nicsp_costodesmant", "autoInc" => "0");
$dalTablealmovinddia["nicsp_valorresidual"] = array("type"=>5,"varname"=>"nicsp_valorresidual", "name" => "nicsp_valorresidual", "autoInc" => "0");
$dalTablealmovinddia["nicsp_valordeterioro"] = array("type"=>5,"varname"=>"nicsp_valordeterioro", "name" => "nicsp_valordeterioro", "autoInc" => "0");
$dalTablealmovinddia["nicsp_basedepreciable"] = array("type"=>5,"varname"=>"nicsp_basedepreciable", "name" => "nicsp_basedepreciable", "autoInc" => "0");
$dalTablealmovinddia["nicsp_costo"] = array("type"=>5,"varname"=>"nicsp_costo", "name" => "nicsp_costo", "autoInc" => "0");
$dalTablealmovinddia["nicsp_codigo_ppe"] = array("type"=>3,"varname"=>"nicsp_codigo_ppe", "name" => "nicsp_codigo_ppe", "autoInc" => "0");
$dalTablealmovinddia["nicsp_vigenciapm"] = array("type"=>2,"varname"=>"nicsp_vigenciapm", "name" => "nicsp_vigenciapm", "autoInc" => "0");
$dalTablealmovinddia["nicsp_politicamaterialidad"] = array("type"=>16,"varname"=>"nicsp_politicamaterialidad", "name" => "nicsp_politicamaterialidad", "autoInc" => "0");
$dalTablealmovinddia["nicsp_vidautil"] = array("type"=>3,"varname"=>"nicsp_vidautil", "name" => "nicsp_vidautil", "autoInc" => "0");
$dalTablealmovinddia["nicsp_fechacorte"] = array("type"=>7,"varname"=>"nicsp_fechacorte", "name" => "nicsp_fechacorte", "autoInc" => "0");
$dalTablealmovinddia["nicsp_dias"] = array("type"=>5,"varname"=>"nicsp_dias", "name" => "nicsp_dias", "autoInc" => "0");
$dalTablealmovinddia["nicsp_meses"] = array("type"=>5,"varname"=>"nicsp_meses", "name" => "nicsp_meses", "autoInc" => "0");
$dalTablealmovinddia["nicsp_depreciamensual"] = array("type"=>5,"varname"=>"nicsp_depreciamensual", "name" => "nicsp_depreciamensual", "autoInc" => "0");
$dalTablealmovinddia["nicsp_depreciaacumulada"] = array("type"=>5,"varname"=>"nicsp_depreciaacumulada", "name" => "nicsp_depreciaacumulada", "autoInc" => "0");
$dalTablealmovinddia["nicsp_fechacorte_hist"] = array("type"=>7,"varname"=>"nicsp_fechacorte_hist", "name" => "nicsp_fechacorte_hist", "autoInc" => "0");
$dalTablealmovinddia["nicsp_depreciaacumulada_hist"] = array("type"=>5,"varname"=>"nicsp_depreciaacumulada_hist", "name" => "nicsp_depreciaacumulada_hist", "autoInc" => "0");
$dalTablealmovinddia["nicsp_vnl"] = array("type"=>5,"varname"=>"nicsp_vnl", "name" => "nicsp_vnl", "autoInc" => "0");
$dalTablealmovinddia["nicsp_vida_remanente"] = array("type"=>5,"varname"=>"nicsp_vida_remanente", "name" => "nicsp_vida_remanente", "autoInc" => "0");
$dalTablealmovinddia["cod_cta"] = array("type"=>3,"varname"=>"cod_cta", "name" => "cod_cta", "autoInc" => "0");
$dalTablealmovinddia["syslastupd"] = array("type"=>135,"varname"=>"syslastupd", "name" => "syslastupd", "autoInc" => "0");
$dalTablealmovinddia["almovinddia_id"]["key"]=true;

$dal_info["dbrf_at_127_0_0_1__almovinddia"] = &$dalTablealmovinddia;
?>