<?php
$dalTableq_global_enservicio = array();
$dalTableq_global_enservicio["di_funcionario"] = array("type"=>200,"varname"=>"di_funcionario", "name" => "di_funcionario", "autoInc" => "0");
$dalTableq_global_enservicio["func_nombres"] = array("type"=>200,"varname"=>"func_nombres", "name" => "func_nombres", "autoInc" => "0");
$dalTableq_global_enservicio["func_dep"] = array("type"=>200,"varname"=>"func_dep", "name" => "func_dep", "autoInc" => "0");
$dalTableq_global_enservicio["func_email"] = array("type"=>200,"varname"=>"func_email", "name" => "func_email", "autoInc" => "0");
$dalTableq_global_enservicio["func_tipovinc"] = array("type"=>16,"varname"=>"func_tipovinc", "name" => "func_tipovinc", "autoInc" => "0");
$dalTableq_global_enservicio["aldevindiv_id"] = array("type"=>3,"varname"=>"aldevindiv_id", "name" => "aldevindiv_id", "autoInc" => "0");
$dalTableq_global_enservicio["almovinddia_id_fk"] = array("type"=>3,"varname"=>"almovinddia_id_fk", "name" => "almovinddia_id_fk", "autoInc" => "0");
$dalTableq_global_enservicio["di_cuenta"] = array("type"=>3,"varname"=>"di_cuenta", "name" => "di_cuenta", "autoInc" => "0");
$dalTableq_global_enservicio["di_codelem"] = array("type"=>3,"varname"=>"di_codelem", "name" => "di_codelem", "autoInc" => "0");
$dalTableq_global_enservicio["di_almacen"] = array("type"=>3,"varname"=>"di_almacen", "name" => "di_almacen", "autoInc" => "0");
$dalTableq_global_enservicio["di_nroplaca"] = array("type"=>200,"varname"=>"di_nroplaca", "name" => "di_nroplaca", "autoInc" => "0");
$dalTableq_global_enservicio["di_nroserie"] = array("type"=>200,"varname"=>"di_nroserie", "name" => "di_nroserie", "autoInc" => "0");
$dalTableq_global_enservicio["di_fechacompra"] = array("type"=>7,"varname"=>"di_fechacompra", "name" => "di_fechacompra", "autoInc" => "0");
$dalTableq_global_enservicio["di_valorultmovto"] = array("type"=>5,"varname"=>"di_valorultmovto", "name" => "di_valorultmovto", "autoInc" => "0");
$dalTableq_global_enservicio["di_valorcompra"] = array("type"=>5,"varname"=>"di_valorcompra", "name" => "di_valorcompra", "autoInc" => "0");
$dalTableq_global_enservicio["di_nroplacastma"] = array("type"=>200,"varname"=>"di_nroplacastma", "name" => "di_nroplacastma", "autoInc" => "0");
$dalTableq_global_enservicio["sys_user"] = array("type"=>200,"varname"=>"sys_user", "name" => "sys_user", "autoInc" => "0");
$dalTableq_global_enservicio["sys_date"] = array("type"=>135,"varname"=>"sys_date", "name" => "sys_date", "autoInc" => "0");
$dalTableq_global_enservicio["sys_time"] = array("type"=>135,"varname"=>"sys_time", "name" => "sys_time", "autoInc" => "0");
$dalTableq_global_enservicio["sys_sts"] = array("type"=>2,"varname"=>"sys_sts", "name" => "sys_sts", "autoInc" => "0");
$dalTableq_global_enservicio["ed_nomelemento"] = array("type"=>200,"varname"=>"ed_nomelemento", "name" => "ed_nomelemento", "autoInc" => "0");
$dalTableq_global_enservicio["edunidad"] = array("type"=>200,"varname"=>"edunidad", "name" => "edunidad", "autoInc" => "0");
$dalTableq_global_enservicio["edmarca"] = array("type"=>3,"varname"=>"edmarca", "name" => "edmarca", "autoInc" => "0");
$dalTableq_global_enservicio["ca_nomcuenta"] = array("type"=>200,"varname"=>"ca_nomcuenta", "name" => "ca_nomcuenta", "autoInc" => "0");
$dalTableq_global_enservicio["ma_nommarca"] = array("type"=>200,"varname"=>"ma_nommarca", "name" => "ma_nommarca", "autoInc" => "0");
$dalTableq_global_enservicio["upd_date"] = array("type"=>135,"varname"=>"upd_date", "name" => "upd_date", "autoInc" => "0");
$dalTableq_global_enservicio["upd_user"] = array("type"=>200,"varname"=>"upd_user", "name" => "upd_user", "autoInc" => "0");
$dalTableq_global_enservicio["upd_status"] = array("type"=>2,"varname"=>"upd_status", "name" => "upd_status", "autoInc" => "0");
$dalTableq_global_enservicio["VRMEJORA"] = array("type"=>5,"varname"=>"VRMEJORA", "name" => "VRMEJORA", "autoInc" => "0");
$dalTableq_global_enservicio["mod_trasnporte"] = array("type"=>2,"varname"=>"mod_trasnporte", "name" => "mod_trasnporte", "autoInc" => "0");
$dalTableq_global_enservicio["verifica_status"] = array("type"=>2,"varname"=>"verifica_status", "name" => "verifica_status", "autoInc" => "0");
$dalTableq_global_enservicio["verifica_user"] = array("type"=>200,"varname"=>"verifica_user", "name" => "verifica_user", "autoInc" => "0");
$dalTableq_global_enservicio["verifica_date"] = array("type"=>135,"varname"=>"verifica_date", "name" => "verifica_date", "autoInc" => "0");
$dalTableq_global_enservicio["cod_cta"] = array("type"=>3,"varname"=>"cod_cta", "name" => "cod_cta", "autoInc" => "0");
$dalTableq_global_enservicio["di_ubica"] = array("type"=>3,"varname"=>"di_ubica", "name" => "di_ubica", "autoInc" => "0");
$dalTableq_global_enservicio["Observaciones"] = array("type"=>200,"varname"=>"Observaciones", "name" => "Observaciones", "autoInc" => "0");
$dalTableq_global_enservicio["nicsp_costodesmant"] = array("type"=>5,"varname"=>"nicsp_costodesmant", "name" => "nicsp_costodesmant", "autoInc" => "0");
$dalTableq_global_enservicio["nicsp_valorresidual"] = array("type"=>5,"varname"=>"nicsp_valorresidual", "name" => "nicsp_valorresidual", "autoInc" => "0");
$dalTableq_global_enservicio["nicsp_valordeterioro"] = array("type"=>5,"varname"=>"nicsp_valordeterioro", "name" => "nicsp_valordeterioro", "autoInc" => "0");
$dalTableq_global_enservicio["nicsp_basedepreciable"] = array("type"=>5,"varname"=>"nicsp_basedepreciable", "name" => "nicsp_basedepreciable", "autoInc" => "0");
$dalTableq_global_enservicio["nicsp_costo"] = array("type"=>5,"varname"=>"nicsp_costo", "name" => "nicsp_costo", "autoInc" => "0");
$dalTableq_global_enservicio["nicsp_codigo_ppe"] = array("type"=>20,"varname"=>"nicsp_codigo_ppe", "name" => "nicsp_codigo_ppe", "autoInc" => "0");
$dalTableq_global_enservicio["nicsp_vigenciapm"] = array("type"=>2,"varname"=>"nicsp_vigenciapm", "name" => "nicsp_vigenciapm", "autoInc" => "0");
$dalTableq_global_enservicio["nicsp_politicamaterialidad"] = array("type"=>16,"varname"=>"nicsp_politicamaterialidad", "name" => "nicsp_politicamaterialidad", "autoInc" => "0");
$dalTableq_global_enservicio["nicsp_vidautil"] = array("type"=>5,"varname"=>"nicsp_vidautil", "name" => "nicsp_vidautil", "autoInc" => "0");
$dalTableq_global_enservicio["nicsp_fechacorte"] = array("type"=>7,"varname"=>"nicsp_fechacorte", "name" => "nicsp_fechacorte", "autoInc" => "0");
$dalTableq_global_enservicio["nicsp_dias"] = array("type"=>5,"varname"=>"nicsp_dias", "name" => "nicsp_dias", "autoInc" => "0");
$dalTableq_global_enservicio["nicsp_meses"] = array("type"=>5,"varname"=>"nicsp_meses", "name" => "nicsp_meses", "autoInc" => "0");
$dalTableq_global_enservicio["nicsp_depreciamensual"] = array("type"=>5,"varname"=>"nicsp_depreciamensual", "name" => "nicsp_depreciamensual", "autoInc" => "0");
$dalTableq_global_enservicio["nicsp_depreciaacumulada"] = array("type"=>5,"varname"=>"nicsp_depreciaacumulada", "name" => "nicsp_depreciaacumulada", "autoInc" => "0");
$dalTableq_global_enservicio["nicsp_vnl"] = array("type"=>5,"varname"=>"nicsp_vnl", "name" => "nicsp_vnl", "autoInc" => "0");
$dalTableq_global_enservicio["idusrglobal_fk"] = array("type"=>3,"varname"=>"idusrglobal_fk", "name" => "idusrglobal_fk", "autoInc" => "0");

$dal_info["dbrf_at_127_0_0_1__q_global_enservicio"] = &$dalTableq_global_enservicio;
?>