<?php

/**
 * 	Dear developer!
 *	Never modify events.php file, it is autogenerated.
 *  Modify PHP/EventTemplates/events.txt instead.
 *
 */

 class eventclass_alcuentasalma  extends eventsBase
{
	function __construct()
	{
	// fill list of events
		$this->events["BeforeMoveNextList"]=true;


	}

//	handlers

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// List page: After record processed
function BeforeMoveNextList(&$data, &$row, &$record, $recordId, $pageObject)
{

		IF($data['ca_recibemovto'] == 'N')
{
$pageObject->hideItem("grid_edit", $recordId);
$pageObject->hideItem("grid_alldetails_link", $recordId);
$pageObject->hideItem("grid_details_link", $recordId); 
$pageObject->hideItem("grid_details_link1", $recordId);
$pageObject->hideItem("grid_checkbox", $recordId);  
$pageObject->hideItem("grid_view", $recordId); 
}


IF($data['tac_codcta'] >= 200)
{
$pageObject->hideItem("grid_details_link1", $recordId);
}
else
{
$pageObject->hideItem("grid_details_link", $recordId);
}

// Place event code here.
// Use "Add Action" button to add code snippets.
;		
} // function BeforeMoveNextList

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		



}
?>
